#! /bin/sh

export ANT_HOME="$(dirname $0)/lib/ant"

if [ -z "$JAVA_HOME" ]; then
  export JAVA_HOME="$(dirname $(dirname $(which javac)))"
  echo "JAVA_HOME was not set, defaulting to: $JAVA_HOME"
fi

"$JAVA_HOME/bin/java" -showversion -classpath "$ANT_HOME/lib/ant-launcher.jar" \
    "-Dant.home=$ANT_HOME" org.apache.tools.ant.launch.Launcher $*
