--
-- Add a new column to identify the type of configuration entry
--
ALTER TABLE APP_CONFIG ADD CONFIG_TYPE VARCHAR(255);
UPDATE APP_CONFIG SET CONFIG_TYPE = 'survey'  WHERE CONFIG_NAME LIKE 'survey.%';
UPDATE APP_CONFIG SET CONFIG_TYPE = 'physician' WHERE CONFIG_NAME LIKE 'physician.%';
UPDATE APP_CONFIG SET CONFIG_TYPE = 'squaretbl' WHERE CONFIG_VALUE LIKE '{"prefix":%';
UPDATE APP_CONFIG SET CONFIG_TYPE = 'custom' WHERE CONFIG_TYPE IS NULL;

ALTER TABLE APP_CONFIG_CHANGE_HISTORY ADD CONFIG_TYPE VARCHAR(255);
UPDATE APP_CONFIG_CHANGE_HISTORY SET CONFIG_TYPE = 'survey' WHERE LOWER(CONFIG_NAME) LIKE 'survey.%';
UPDATE APP_CONFIG_CHANGE_HISTORY SET CONFIG_TYPE = 'physici0an' WHERE lower(CONFIG_NAME) LIKE 'physician.%';
UPDATE APP_CONFIG_CHANGE_HISTORY SET CONFIG_TYPE = 'squaretable' WHERE lower(CONFIG_VALUE) LIKE '{"prefix":%';
UPDATE APP_CONFIG_CHANGE_HISTORY SET CONFIG_TYPE = 'custom' WHERE CONFIG_TYPE IS NULL;

--
-- Change the value column to be a clob to accommodate much larger values
--
ALTER TABLE APP_CONFIG ADD CONFIG_VALUE_CLOB TEXT;
UPDATE APP_CONFIG SET CONFIG_VALUE_CLOB = CONFIG_VALUE;
ALTER TABLE APP_CONFIG DROP COLUMN CONFIG_VALUE;
ALTER TABLE APP_CONFIG RENAME COLUMN CONFIG_VALUE_CLOB TO CONFIG_VALUE;
ALTER TABLE APP_CONFIG ALTER CONFIG_TYPE TYPE VARCHAR(255);
ALTER TABLE APP_CONFIG ALTER CONFIG_TYPE SET NOT NULL;
ALTER TABLE APP_CONFIG DROP CONSTRAINT APP_CONFIG_SITE_FK;

ALTER TABLE APP_CONFIG_CHANGE_HISTORY ADD CONFIG_VALUE_CLOB TEXT;
UPDATE APP_CONFIG_CHANGE_HISTORY SET CONFIG_VALUE_CLOB = CONFIG_VALUE;
ALTER TABLE APP_CONFIG_CHANGE_HISTORY DROP COLUMN CONFIG_VALUE;
ALTER TABLE APP_CONFIG_CHANGE_HISTORY RENAME COLUMN CONFIG_VALUE_CLOB TO CONFIG_VALUE;
ALTER TABLE APP_CONFIG_CHANGE_HISTORY ALTER CONFIG_TYPE TYPE VARCHAR(255);
ALTER TABLE APP_CONFIG_CHANGE_HISTORY ALTER CONFIG_TYPE SET NOT NULL;
