/*
 * Sample query for getting appointments out of Clarity (the EPIC data warehouse).
 *
 * This is an old version, you probably want to use appt_sched_all_lang.sql instead.
 */
SELECT DISTINCT
      PAT.PAT_ID,
      PAT.PAT_FIRST_NAME,
      PAT.PAT_LAST_NAME,
      PAT.PAT_MRN_ID AS MRN,
      PAT.ADD_LINE_1,
      PAT.ADD_LINE_2,
      PAT.CITY,
      PAT.ZIP,
      PAT.HOME_PHONE,
      PAT.WORK_PHONE,
      PAT.EMAIL_ADDRESS,
      TO_CHAR(PAT.BIRTH_DATE,'MM/DD/YYYY') AS DOB,
      TO_CHAR(PEREF.APPT_TIME,'MM/DD/YYYY') AS APPOINTMENT_DATE,
      TO_CHAR(PEREF.APPT_TIME,'HH24:MI') AS APPOINTMENT_TIME,
      CP.PRC_ABBR AS VISIT_TYPE,
      CP.PRC_ID AS VISIT_TYPE_ID,
      PEREF.PAT_ENC_CSN_ID,
      ENC_PROV.PROV_NAME AS ENC_PROV_NAME,
      ENC_PROV.PROV_ID,
      CD_PAT_ENC.DEPARTMENT_NAME AS PAT_ENC_DEPARTMENT,
      CD_PAT_ENC.DEPARTMENT_ID AS PAT_ENC_DEPARTMENT_ID,
      (select name from zc_sex s where s.rcpt_mem_sex_c=pat.sex_c) as sex,
      ZEG.NAME AS ETHNICITY,
      (SELECT NAME FROM PATIENT_RACE PR INNER JOIN ZC_PATIENT_RACE ZPR ON ZPR.PATIENT_RACE_C = PR.PATIENT_RACE_C 
       WHERE ZPR.NAME IS NOT NULL AND PR.PAT_ID = PAT.PAT_ID AND LINE=1) AS PATIENT_RACE,
      PEREF.enc_type_c,
      PEREF.appt_status_c,
      PEREF.appt_cancel_date,
      PEREF.appt_serial_no,
      PEREF.appt_block_c,
      PEREF.cancel_reason_cmt
FROM
  (
    SELECT
    PE.APPT_TIME,
    PE.APPT_MADE_DATE,
    PE.REFERRAL_ID,
    PE.PAT_ID AS PATIENT_ID,
    PE.DEPARTMENT_ID,
    REF.REFD_TO_DEPT_ID,
    REF.PCP_PROV_ID,
    PE.ENC_TYPE_C,
    PE.PAT_ENC_CSN_ID,
    PE.VISIT_PROV_ID,
    REF.REFERRAL_PROV_ID,
    PE.APPT_STATUS_C,
    REF.RFL_CLASS_C,
    REF.REFERRING_PROV_ID,
    APPT_PRC_ID,
    PE.appt_cancel_date,
    PE.appt_serial_no,
    PE.cancel_reason_cmt,
    PE.APPT_BLOCK_C
    FROM PAT_ENC PE LEFT OUTER JOIN REFERRAL REF ON REF.REFERRAL_ID = PE.REFERRAL_ID
  ) PEREF 
  INNER JOIN PATIENT PAT ON PEREF.PATIENT_ID = PAT.PAT_ID
  LEFT OUTER JOIN CLARITY_DEP CD ON CD.DEPARTMENT_ID = PEREF.REFD_TO_DEPT_ID
  LEFT OUTER JOIN ZC_ETHNIC_GROUP ZEG ON ZEG.ETHNIC_GROUP_C = PAT.ETHNIC_GROUP_C
  LEFT OUTER JOIN ZC_RFL_CLASS ZRC ON ZRC.RFL_CLASS_C = PEREF.RFL_CLASS_C
  LEFT OUTER JOIN CLARITY_SER CS_REF_TO ON CS_REF_TO.PROV_ID = PEREF.REFERRAL_PROV_ID
  LEFT OUTER JOIN CLARITY_SER CS_REF_BY ON CS_REF_BY.PROV_ID = PEREF.REFERRING_PROV_ID
  LEFT OUTER JOIN CLARITY_SER_ADDR CE ON CE.PROV_ID = CS_REF_BY.PROV_ID AND CE.LINE = 1
  LEFT OUTER JOIN CLARITY_SER CS_PCP ON CS_PCP.PROV_ID = PEREF.PCP_PROV_ID
  LEFT OUTER JOIN CLARITY_PRC CP ON CP.PRC_ID = PEREF.APPT_PRC_ID
  LEFT OUTER JOIN CLARITY_SER ENC_PROV ON ENC_PROV.PROV_ID = PEREF.VISIT_PROV_ID
  LEFT OUTER JOIN ZC_APPT_STATUS ZAS ON ZAS.APPT_STATUS_C = PEREF.APPT_STATUS_C
  LEFT OUTER JOIN ZC_STATE ZSTATE ON CE.STATE_C = ZSTATE.STATE_C
  LEFT OUTER JOIN ZC_STATE ZS ON ZS.STATE_C = PAT.STATE_C
  INNER JOIN CLARITY_DEP CD_PAT_ENC ON CD_PAT_ENC.DEPARTMENT_ID = PEREF.DEPARTMENT_ID
WHERE PEREF.APPT_TIME >= TRUNC(SYSDATE)-30
;
