FROM openjdk:8-jdk@sha256:7b20cf48488e50c7692a8b3c79a76391ccba953ce6417c1cd0f3fbebaeb87af9
# "Created": "2020-04-16T10:20:54.664620226Z", "JAVA_VERSION=8u252"

# FROM openjdk@sha256:1e86cb6c95538a8034897089058fe7647923272daed87f90f50567b8abe3bf03
# "Created": "2019-04-04T22:31:20.178776201Z","JAVA_VERSION=11.0.3","JAVA_DEBIAN_VERSION=11.0.3+1-1~bpo9+1"

ENV JAVA_OPTIONS=-Xmx512m
# This can be a comma-separated list, with properties taken from the first file to contain the key
ENV PROPERTIES=/app/conf/app.properties
# This controls the web application context
ENV war=choir

ADD movewar.sh /app/bin/movewar.sh
RUN cp /usr/share/zoneinfo/@docker.registry.timezone@ /etc/localtime \
    && echo @docker.registry.timezone@ > /etc/timezone \
    && mkdir -p /app/conf /app/logs /app/bin /app/work /app/appointments \
    && chmod +x /app/bin/movewar.sh

COPY tomcat tomcat-choir /tomcat/
COPY clinic.war /app/work/ROOT.war

VOLUME /app/logs
EXPOSE 8080

WORKDIR /app
CMD /app/bin/movewar.sh
