package edu.stanford.survey.server.promis;

import edu.stanford.survey.server.CatAlgorithm.ItemBank;

import static edu.stanford.survey.server.ItemBanks.*;

/**
 * Item bank for PROMIS generated from: Satisfaction Roles Activities 612ADAF7-0C0E-4D16-9236-C8006F84759A.json
 */
public class PromisSatisfactionRolesActivities {

  private static final ItemBank bank = itemBank(0.0, 0.0, 4, 12, 3.0,
    item("RP14_CaPS", "", "I am satisfied with my current level of family activities", "", 3.28266, new double[] { -1.566, -1.0287, -0.1879, 0.5779 }, -1, "", 
      response("Not at all", 1),
      response("A little bit", 2),
      response("Somewhat", 3),
      response("Quite a bit", 4),
      response("Very much", 5)
    ),
    item("RP7_CaPS", "", "I am satisfied with my ability to maintain friendships", "", 2.1202, new double[] { -2.2107, -1.4344, -0.6247, 0.3491 }, -1, "", 
      response("Not at all", 1),
      response("A little bit", 2),
      response("Somewhat", 3),
      response("Quite a bit", 4),
      response("Very much", 5)
    ),
    item("SRPSAT03_CaPS", "", "I am satisfied with how often I go out for entertainment", "", 2.52883, new double[] { -1.3463, -0.7671, 0.0167, 0.791 }, -1, "", 
      response("Not at all", 1),
      response("A little bit", 2),
      response("Somewhat", 3),
      response("Quite a bit", 4),
      response("Very much", 5)
    ),
    item("SRPSAT04_CaPS", "", "I am satisfied with my ability to socialize with friends", "", 2.80672, new double[] { -1.8121, -1.1304, -0.2962, 0.4932 }, -1, "", 
      response("Not at all", 1),
      response("A little bit", 2),
      response("Somewhat", 3),
      response("Quite a bit", 4),
      response("Very much", 5)
    ),
    item("SRPSAT05_CaPS", "", "I am satisfied with the amount of time I spend doing leisure activities with others", "", 3.55345, new double[] { -1.4126, -0.8334, 0.0309, 0.7348 }, -1, "", 
      response("Not at all", 1),
      response("A little bit", 2),
      response("Somewhat", 3),
      response("Quite a bit", 4),
      response("Very much", 5)
    ),
    item("SRPSAT05r1", "", "I am satisfied with the amount of time I spend doing leisure activities", "", 3.17814, new double[] { -1.4943, -0.8917, -0.0929, 0.654 }, -1, "", 
      response("Not at all", 1),
      response("A little bit", 2),
      response("Somewhat", 3),
      response("Quite a bit", 4),
      response("Very much", 5)
    ),
    item("SRPSAT06r1", "", "I am satisfied with my ability to do things for my family", "", 3.8899, new double[] { -1.6407, -1.1209, -0.3121, 0.4354 }, -1, "", 
      response("Not at all", 1),
      response("A little bit", 2),
      response("Somewhat", 3),
      response("Quite a bit", 4),
      response("Very much", 5)
    ),
    item("SRPSAT07r1", "", "I am satisfied with how much work I can do (include work at home)", "", 3.86015, new double[] { -1.2958, -0.8215, -0.0868, 0.5918 }, -1, "", 
      response("Not at all", 1),
      response("A little bit", 2),
      response("Somewhat", 3),
      response("Quite a bit", 4),
      response("Very much", 5)
    ),
    item("SRPSAT08r1", "", "I feel good about my ability to do things for my family", "", 3.58485, new double[] { -1.7093, -1.1283, -0.3736, 0.3393 }, -1, "", 
      response("Not at all", 1),
      response("A little bit", 2),
      response("Somewhat", 3),
      response("Quite a bit", 4),
      response("Very much", 5)
    ),
    item("SRPSAT09r1", "", "I am satisfied with my ability to do the work that is really important to me (include work at home)", "", 3.73571, new double[] { -1.3662, -0.9007, -0.2037, 0.4976 }, -1, "", 
      response("Not at all", 1),
      response("A little bit", 2),
      response("Somewhat", 3),
      response("Quite a bit", 4),
      response("Very much", 5)
    ),
    item("SRPSAT10r1", "", "I am satisfied with my current level of social activity", "", 2.72154, new double[] { -1.5418, -0.9085, -0.0113, 0.7699 }, -1, "", 
      response("Not at all", 1),
      response("A little bit", 2),
      response("Somewhat", 3),
      response("Quite a bit", 4),
      response("Very much", 5)
    ),
    item("SRPSAT15_CaPS", "", "I am satisfied with my ability to participate in family activities", "", 3.44286, new double[] { -1.6739, -1.1491, -0.3831, 0.3607 }, -1, "", 
      response("Not at all", 1),
      response("A little bit", 2),
      response("Somewhat", 3),
      response("Quite a bit", 4),
      response("Very much", 5)
    ),
    item("SRPSAT17_CaPS", "", "I am satisfied with the extent of my social activities outside my home", "", 3.38678, new double[] { -1.2491, -0.7504, -0.0247, 0.7282 }, -1, "", 
      response("Not at all", 1),
      response("A little bit", 2),
      response("Somewhat", 3),
      response("Quite a bit", 4),
      response("Very much", 5)
    ),
    item("SRPSAT19r1", "", "I am satisfied with my ability to do all of the community activities that are really important to me", "", 3.52885, new double[] { -1.2391, -0.7194, -0.0294, 0.6925 }, -1, "", 
      response("Not at all", 1),
      response("A little bit", 2),
      response("Somewhat", 3),
      response("Quite a bit", 4),
      response("Very much", 5)
    ),
    item("SRPSAT20r1", "", "I am satisfied with my ability to do things for my friends", "", 4.0996, new double[] { -1.5382, -0.9343, -0.1488, 0.6153 }, -1, "", 
      response("Not at all", 1),
      response("A little bit", 2),
      response("Somewhat", 3),
      response("Quite a bit", 4),
      response("Very much", 5)
    ),
    item("SRPSAT21r1", "", "I am satisfied with the amount of time I spend doing work (include work at home)", "", 3.43898, new double[] { -1.4502, -0.9252, -0.0938, 0.631 }, -1, "", 
      response("Not at all", 1),
      response("A little bit", 2),
      response("Somewhat", 3),
      response("Quite a bit", 4),
      response("Very much", 5)
    ),
    item("SRPSAT22r1", "", "I am happy with how much I do for my family", "", 3.29431, new double[] { -1.7279, -1.1114, -0.3347, 0.3792 }, -1, "", 
      response("Not at all", 1),
      response("A little bit", 2),
      response("Somewhat", 3),
      response("Quite a bit", 4),
      response("Very much", 5)
    ),
    item("SRPSAT23_CaPS", "", "I am satisfied with my ability to do leisure activities with others", "", 4.5628, new double[] { -1.3309, -0.827, -0.0706, 0.6191 }, -1, "", 
      response("Not at all", 1),
      response("A little bit", 2),
      response("Somewhat", 3),
      response("Quite a bit", 4),
      response("Very much", 5)
    ),
    item("SRPSAT23r1", "", "I am satisfied with my ability to do leisure activities", "", 4.48931, new double[] { -1.4675, -0.8725, -0.1462, 0.5295 }, -1, "", 
      response("Not at all", 1),
      response("A little bit", 2),
      response("Somewhat", 3),
      response("Quite a bit", 4),
      response("Very much", 5)
    ),
    item("SRPSAT24r1", "", "I am satisfied with my ability to work (include work at home)", "", 3.69555, new double[] { -1.2892, -0.8493, -0.1622, 0.5157 }, -1, "", 
      response("Not at all", 1),
      response("A little bit", 2),
      response("Somewhat", 3),
      response("Quite a bit", 4),
      response("Very much", 5)
    ),
    item("SRPSAT25r1", "", "I am satisfied with my current level of activities with my friends", "", 3.19416, new double[] { -1.4315, -0.8448, 0.0326, 0.7595 }, -1, "", 
      response("Not at all", 1),
      response("A little bit", 2),
      response("Somewhat", 3),
      response("Quite a bit", 4),
      response("Very much", 5)
    ),
    item("SRPSAT29_CaPS", "", "I am satisfied with my ability to engage in activities with friends", "", 3.66543, new double[] { -1.5004, -0.9263, -0.1473, 0.5544 }, -1, "", 
      response("Not at all", 1),
      response("A little bit", 2),
      response("Somewhat", 3),
      response("Quite a bit", 4),
      response("Very much", 5)
    ),
    item("SRPSAT33_CaPS", "", "I am satisfied with my ability to do things for fun with others", "", 4.57753, new double[] { -1.4283, -0.8224, -0.0924, 0.6083 }, -1, "", 
      response("Not at all", 1),
      response("A little bit", 2),
      response("Somewhat", 3),
      response("Quite a bit", 4),
      response("Very much", 5)
    ),
    item("SRPSAT33r1", "", "I am satisfied with my ability to do things for fun outside my home", "", 4.74952, new double[] { -1.2522, -0.7227, -0.0789, 0.5535 }, -1, "", 
      response("Not at all", 1),
      response("A little bit", 2),
      response("Somewhat", 3),
      response("Quite a bit", 4),
      response("Very much", 5)
    ),
    item("SRPSAT34r1", "", "I feel good about my ability to do things for my friends", "", 4.04326, new double[] { -1.6063, -0.9906, -0.1608, 0.554 }, -1, "", 
      response("Not at all", 1),
      response("A little bit", 2),
      response("Somewhat", 3),
      response("Quite a bit", 4),
      response("Very much", 5)
    ),
    item("SRPSAT35r1", "", "The quality of my work is as good as I want it to be (include work at home)", "", 2.81527, new double[] { -1.4112, -0.9383, -0.1125, 0.7006 }, -1, "", 
      response("Not at all", 1),
      response("A little bit", 2),
      response("Somewhat", 3),
      response("Quite a bit", 4),
      response("Very much", 5)
    ),
    item("SRPSAT36r1", "", "I am happy with how much I do for my friends", "", 3.53007, new double[] { -1.5887, -0.9378, -0.093, 0.756 }, -1, "", 
      response("Not at all", 1),
      response("A little bit", 2),
      response("Somewhat", 3),
      response("Quite a bit", 4),
      response("Very much", 5)
    ),
    item("SRPSAT37r1", "", "I am satisfied with the amount of time I spend visiting friends", "", 3.03169, new double[] { -1.3584, -0.7495, 0.0851, 0.9025 }, -1, "", 
      response("Not at all", 1),
      response("A little bit", 2),
      response("Somewhat", 3),
      response("Quite a bit", 4),
      response("Very much", 5)
    ),
    item("SRPSAT38_CaPS", "", "I am satisfied with the amount of time I spend doing things for my family", "", 3.84217, new double[] { -1.59, -1.015, -0.2373, 0.4936 }, -1, "", 
      response("Not at all", 1),
      response("A little bit", 2),
      response("Somewhat", 3),
      response("Quite a bit", 4),
      response("Very much", 5)
    ),
    item("SRPSAT38r1", "", "I am satisfied with the amount of time I spend performing my daily routines", "", 3.53917, new double[] { -1.4973, -0.9641, -0.1241, 0.6099 }, -1, "", 
      response("Not at all", 1),
      response("A little bit", 2),
      response("Somewhat", 3),
      response("Quite a bit", 4),
      response("Very much", 5)
    ),
    item("SRPSAT39r1", "", "I am satisfied with my ability to do household chores/tasks", "", 3.57274, new double[] { -1.4154, -0.8726, -0.133, 0.5453 }, -1, "", 
      response("Not at all", 1),
      response("A little bit", 2),
      response("Somewhat", 3),
      response("Quite a bit", 4),
      response("Very much", 5)
    ),
    item("SRPSAT41_CaPS", "", "I am satisfied with the extent of my social activities with groups of people", "", 3.1097, new double[] { -1.4639, -0.878, -0.0355, 0.6631 }, -1, "", 
      response("Not at all", 1),
      response("A little bit", 2),
      response("Somewhat", 3),
      response("Quite a bit", 4),
      response("Very much", 5)
    ),
    item("SRPSAT43_CaPS", "", "I am satisfied with my ability to keep in touch with others", "", 2.31934, new double[] { -2.1968, -1.331, -0.3673, 0.527 }, -1, "", 
      response("Not at all", 1),
      response("A little bit", 2),
      response("Somewhat", 3),
      response("Quite a bit", 4),
      response("Very much", 5)
    ),
    item("SRPSAT45_CaPS", "", "I am satisfied with my ability to meet the needs of my family", "", 3.61767, new double[] { -1.646, -1.1709, -0.3477, 0.3923 }, -1, "", 
      response("Not at all", 1),
      response("A little bit", 2),
      response("Somewhat", 3),
      response("Quite a bit", 4),
      response("Very much", 5)
    ),
    item("SRPSAT46_CaPS", "", "I am satisfied with my ability to meet the needs of my friends", "", 3.61734, new double[] { -1.7176, -1.0184, -0.1624, 0.7194 }, -1, "", 
      response("Not at all", 1),
      response("A little bit", 2),
      response("Somewhat", 3),
      response("Quite a bit", 4),
      response("Very much", 5)
    ),
    item("SRPSAT47_CaPS", "", "I am satisfied with my ability to do regular personal responsibilities", "", 3.57114, new double[] { -1.7846, -1.1755, -0.4262, 0.3321 }, -1, "", 
      response("Not at all", 1),
      response("A little bit", 2),
      response("Somewhat", 3),
      response("Quite a bit", 4),
      response("Very much", 5)
    ),
    item("SRPSAT47r1", "", "I am satisfied with my ability to do regular personal and household responsibilities", "", 4.02722, new double[] { -1.4925, -0.934, -0.2626, 0.4066 }, -1, "", 
      response("Not at all", 1),
      response("A little bit", 2),
      response("Somewhat", 3),
      response("Quite a bit", 4),
      response("Very much", 5)
    ),
    item("SRPSAT48r1", "", "I am satisfied with my ability to do things for fun at home (like reading, listening to music, etc.)", "", 2.31882, new double[] { -2.2438, -1.458, -0.7345, 0.1868 }, -1, "", 
      response("Not at all", 1),
      response("A little bit", 2),
      response("Somewhat", 3),
      response("Quite a bit", 4),
      response("Very much", 5)
    ),
    item("SRPSAT49r1", "", "I am satisfied with my ability to perform my daily routines", "", 4.16999, new double[] { -1.5875, -1.0594, -0.3223, 0.3584 }, -1, "", 
      response("Not at all", 1),
      response("A little bit", 2),
      response("Somewhat", 3),
      response("Quite a bit", 4),
      response("Very much", 5)
    ),
    item("SRPSAT50r1", "", "I am satisfied with my ability to meet the needs of those who depend on me", "", 3.47005, new double[] { -1.6451, -1.1485, -0.3461, 0.4891 }, -1, "", 
      response("Not at all", 1),
      response("A little bit", 2),
      response("Somewhat", 3),
      response("Quite a bit", 4),
      response("Very much", 5)
    ),
    item("SRPSAT51_CaPS", "", "I am satisfied with my ability to run errands for others", "", 3.07995, new double[] { -1.3475, -0.8401, -0.1537, 0.6006 }, -1, "", 
      response("Not at all", 1),
      response("A little bit", 2),
      response("Somewhat", 3),
      response("Quite a bit", 4),
      response("Very much", 5)
    ),
    item("SRPSAT51r1", "", "I am satisfied with my ability to run errands", "", 3.24071, new double[] { -1.4785, -1.0396, -0.4012, 0.2734 }, -1, "", 
      response("Not at all", 1),
      response("A little bit", 2),
      response("Somewhat", 3),
      response("Quite a bit", 4),
      response("Very much", 5)
    ),
    item("SRPSAT52_CaPS", "", "I am satisfied with my ability to do all of the group activities that are really important to me", "", 4.60972, new double[] { -1.2893, -0.8065, -0.0736, 0.5821 }, -1, "", 
      response("Not at all", 1),
      response("A little bit", 2),
      response("Somewhat", 3),
      response("Quite a bit", 4),
      response("Very much", 5)
    ),
    item("SRPSAT52r1", "", "I am satisfied with my ability to do all of the leisure activities that are really important to me", "", 4.49267, new double[] { -1.2558, -0.7838, -0.1158, 0.5135 }, -1, "", 
      response("Not at all", 1),
      response("A little bit", 2),
      response("Somewhat", 3),
      response("Quite a bit", 4),
      response("Very much", 5)
    )
  );

  public static ItemBank bank() {
    return bank;
  }
}