package edu.stanford.survey.server.promis;

import edu.stanford.survey.server.CatAlgorithm.ItemBank;
import static edu.stanford.survey.server.ItemBanks.*;

/**
 * Item bank for PROMIS generated from: PhysicalFunction v1.2 56296D2D-C919-40F1-AFC7-6F544FCA7772.json
 */
public class PromisPhysicalFunction2 {

  private static final ItemBank bank = itemBank(0.0, 0.0, 4, 12, 3.0, 
  item("PFA1", "", "Does your health now limit you in doing vigorous activities, such as running, lifting heavy objects, participating in strenuous sports?", "", 3.31447, new double[] { -1.1155, -0.5038, 0.1276, 0.6012 }, -1, "", 
    response("Not at all", 5),
    response("Very little", 4),
    response("Somewhat", 3),
    response("Quite a lot", 2),
    response("Cannot do", 1)
  ),
  item("PFA10", "", "Are you able to stand for one hour?", "", 3.37529, new double[] { -1.7469, -1.3522, -0.9182, -0.3361 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFA11", "", "Are you able to do chores such as vacuuming or yard work?", "", 4.83487, new double[] { -1.9837, -1.5298, -1.1056, -0.4545 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFA12", "", "Are you able to push open a heavy door?", "", 3.45638, new double[] { -2.7039, -2.0429, -1.52, -0.7504 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFA13", "", "Are you able to exercise for an hour?", "", 2.95971, new double[] { -1.4114, -0.9872, -0.415, 0.3052 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFA14r1", "", "Are you able to carry a heavy object (over 10 pounds /5 kg)?", "", 3.43, new double[] { -2.21, -1.74, -1.25, -0.66 }, -1, "",
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFA15", "", "Are you able to stand up from an armless straight chair?", "", 3.19284, new double[] { -2.8025, -2.1119, -1.5397, -0.7702 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFA16r1", "", "Are you able to dress yourself, including tying shoelaces and buttoning your clothes?", "", 3.37, new double[] { -3.14, -2.56, -1.91, -1.24 }, -1, "",
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFA17", "", "Are you able to reach into a high cupboard?", "", 2.17924, new double[] { -2.7236, -2.3092, -1.7469, -0.928 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFA18", "", "Are you able to use a hammer to pound a nail?", "", 2.48332, new double[] { -2.9209, -2.4671, -1.9442, -1.3424 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFA19r1", "", "Are you able to run or jog for two miles (3 km)?", "", 2.66, new double[] { -0.49, -0.05, 0.04, 0.51, 1.11 }, -1, "",
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFA20", "", "Are you able to cut your food using eating utensils?", "", 2.60495, new double[] { -3.3353, -2.8716, -2.4967, -1.9541 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFA21", "", "Are you able to go up and down stairs at a normal pace?", "", 4.23685, new double[] { -1.885, -1.4805, -1.0464, -0.3953 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFA23", "", "Are you able to go for a walk of at least 15 minutes?", "", 4.28753, new double[] { -1.9146, -1.5792, -1.1944, -0.6814 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFA25", "", "Are you able to do yard work like raking leaves, weeding, or pushing a lawn mower?", "", 4.33821, new double[] { -1.6186, -1.224, -0.8195, -0.1979 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFA28", "", "Are you able to open a can with a hand can opener?", "", 2.17924, new double[] { -3.1873, -2.5066, -1.9442, -1.1747 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFA29r1", "", "Are you able to pull heavy objects (10 pounds/ 5 kg) towards yourself?", "", 2.88, new double[] { -2.6, -2.06, -1.51, -0.93 }, -1, "",
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFA3", "", "Does your health now limit you in bending, kneeling, or stooping?", "", 2.94958, new double[] { -2.25, -1.2635, -0.563, 0.029 }, -1, "", 
    response("Not at all", 5),
    response("Very little", 4),
    response("Somewhat", 3),
    response("Quite a lot", 2),
    response("Cannot do", 1)
  ),
  item("PFA30", "", "Are you able to step up and down curbs?", "", 4.07467, new double[] { -2.8617, -2.2698, -1.7272, -1.0267 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFA31r1", "", "Are you able to get up from the floor from lying on your back without help?", "", 3.26, new double[] { -2.13, -1.55, -1.05, -0.31 }, -1, "",
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFA32", "", "Are you able to stand with your knees straight?", "", 3.10162, new double[] { -2.7137, -2.2402, -1.7863, -1.224 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFA33", "", "Are you able to exercise hard for half an hour?", "", 2.75699, new double[] { -1.3917, -0.9478, -0.3459, 0.3447 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFA34", "", "Are you able to wash your back?", "", 2.1691, new double[] { -2.546, -2.0133, -1.4114, -0.5433 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFA35", "", "Are you able to open and close a zipper?", "", 2.36169, new double[] { -3.7694, -3.0788, -2.4671, -1.8455 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFA36", "", "Are you able to put on and take off a coat or jacket?", "", 2.6455, new double[] { -3.9864, -3.1281, -2.3684, -1.5693 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFA37", "", "Are you able to stand for short periods of time?", "", 3.49692, new double[] { -3.138, -2.2796, -1.7666, -1.224 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFA38", "", "Are you able to dry your back with a towel?", "", 2.80767, new double[] { -3.0294, -2.5066, -1.9442, -1.3917 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFA39r1", "", "Are you able to run at a fast pace for two miles (3 km)?", "", 2.16, new double[] { -0.13, 0.38, 1.02, 1.59 }, -1, "",
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFA4", "", "Does your health now limit you in doing heavy work around the house like scrubbing floors, or lifting or moving heavy furniture?", "", 4.39902, new double[] { -1.5594, -0.9773, -0.415, 0.0586 }, -1, "", 
    response("Not at all", 5),
    response("Very little", 4),
    response("Somewhat", 3),
    response("Quite a lot", 2),
    response("Cannot do", 1)
  ),
  item("PFA40", "", "Are you able to turn a key in a lock?", "", 2.08802, new double[] { -3.9371, -3.5129, -2.6644, -1.9541 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFA41", "", "Are you able to squat and get up?", "", 3.0408, new double[] { -1.7666, -1.2832, -0.7998, -0.0105 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFA42", "", "Are you able to carry a laundry basket up a flight of stairs?", "", 4.39902, new double[] { -1.8357, -1.4509, -1.0267, -0.4249 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFA44", "", "Are you able to put on a shirt or blouse?", "", 3.23338, new double[] { -3.4142, -2.99, -2.4178, -1.7173 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFA45", "", "Are you able to get out of bed into a chair?", "", 3.38542, new double[] { -3.3846, -2.7631, -2.2007, -1.4904 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFA47", "", "Are you able to pull on trousers?", "", 3.31447, new double[] { -3.1774, -2.7335, -2.0823, -1.3522 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFA48", "", "Are you able to peel fruit?", "", 2.2806, new double[] { -3.5918, -2.9604, -2.5066, -1.8455 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFA49", "", "Are you able to bend or twist your back?", "", 2.0272, new double[] { -3.1774, -2.2007, -1.52, -0.6616 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFA5", "", "Does your health now limit you in lifting or carrying groceries?", "", 4.13549, new double[] { -2.3684, -1.6186, -1.0365, -0.5334 }, -1, "", 
    response("Not at all", 5),
    response("Very little", 4),
    response("Somewhat", 3),
    response("Quite a lot", 2),
    response("Cannot do", 1)
  ),
  item("PFA50", "", "Are you able to brush your teeth?", "", 2.72658, new double[] { -3.7792, -3.3155, -2.8617, -2.3487 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFA51", "", "Are you able to sit on the edge of a bed?", "", 3.01039, new double[] { -3.6017, -3.1182, -2.5559, -2.0231 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFA52", "", "Are you able to tie your shoelaces?", "", 2.48332, new double[] { -2.8913, -2.3684, -1.8554, -1.0859 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFA53", "", "Are you able to run errands and shop?", "", 4.43957, new double[] { -2.546, -1.9738, -1.4509, -0.8195 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFA54", "", "Are you able to button your shirt?", "", 2.14883, new double[] { -3.868, -3.286, -2.6151, -1.9245 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFA55", "", "Are you able to wash and dry your body?", "", 3.57801, new double[] { -3.3451, -2.6545, -2.0725, -1.4805 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFA56", "", "Are you able to get in and out of a car?", "", 3.20298, new double[] { -3.5721, -2.6841, -1.9442, -1.0661 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFA6", "", "Does your health now limit you in bathing or dressing yourself?", "", 3.02053, new double[] { -3.7299, -2.8223, -2.0133, -1.4608 }, -1, "", 
    response("Not at all", 5),
    response("Very little", 4),
    response("Somewhat", 3),
    response("Quite a lot", 2),
    response("Cannot do", 1)
  ),
  item("PFA8", "", "Are you able to move a chair from one room to another?", "", 3.55774, new double[] { -2.4474, -1.9639, -1.4904, -0.8392 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFA9", "", "Are you able to bend down and pick up clothing from the floor?", "", 3.09148, new double[] { -2.9209, -2.2106, -1.6285, -0.8984 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFB1", "", "Does your health now limit you in doing moderate work around the house like vacuuming, sweeping floors or carrying in groceries?", "", 4.38889, new double[] { -2.4474, -1.6384, -1.076, -0.632 }, -1, "", 
    response("Not at all", 5),
    response("Very little", 4),
    response("Somewhat", 3),
    response("Quite a lot", 2),
    response("Cannot do", 1)
  ),
  item("PFB10", "", "Are you able to climb up five steps?", "", 3.73005, new double[] { -2.5953, -2.0725, -1.5792, -1.0859 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFB11", "", "Are you able to wash dishes, pots, and utensils by hand while standing at a sink?", "", 3.70978, new double[] { -2.6841, -2.2204, -1.6581, -1.1648 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFB12", "", "Are you able to make a bed, including spreading and tucking in bed sheets?", "", 4.1963, new double[] { -2.5263, -2.0231, -1.52, -0.9675 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFB13", "", "Are you able to carry a shopping bag or briefcase?", "", 4.28753, new double[] { -2.7433, -2.2007, -1.7567, -1.2141 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFB14", "", "Are you able to take a tub bath?", "", 2.96985, new double[] { -2.1514, -1.8751, -1.589, -1.0957 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFB17", "", "Are you able to put on and take off your socks?", "", 2.51373, new double[] { -3.4241, -2.5559, -2.0527, -1.2437 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFB18", "", "Are you able to shave your face or apply makeup?", "", 2.30087, new double[] { -3.4537, -3.207, -2.6348, -2.0823 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFB21", "", "Are you able to pick up coins from a table top?", "", 2.32114, new double[] { -3.868, -3.0097, -2.3882, -1.6877 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFB22", "", "Are you able to hold a plate full of food?", "", 3.11175, new double[] { -3.6214, -2.7828, -2.2895, -1.5989 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFB24", "", "Are you able to run a short distance, such as to catch a bus?", "", 3.84154, new double[] { -1.4114, -1.0859, -0.7406, -0.1289 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFB25", "", "Are you able to push open a door after turning the knob?", "", 2.7874, new double[] { -3.5326, -3.0294, -2.4178, -1.7567 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFB26", "", "Are you able to shampoo your hair?", "", 3.32461, new double[] { -3.1676, -2.8815, -2.3388, -1.7567 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFB27", "", "Are you able to tie a knot or a bow?", "", 2.29074, new double[] { -3.4438, -3.0689, -2.5657, -1.8159 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFB28r1", "", "Are you able to lift 10 pounds (5 kg) above your shoulder?", "", 2.66, new double[] { -2.28, -1.89, -1.43, -0.78 }, -1, "",
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFB3", "", "Does your health now limit you in putting a trash bag outside?", "", 4.01386, new double[] { -2.5855, -2.0823, -1.6186, -1.1451 }, -1, "", 
    response("Not at all", 5),
    response("Very little", 4),
    response("Somewhat", 3),
    response("Quite a lot", 2),
    response("Cannot do", 1)
  ),
  item("PFB30", "", "Are you able to open a new milk carton?", "", 2.04747, new double[] { -4.0456, -3.4043, -2.7137, -1.7567 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFB32", "", "Are you able to stand unsupported for 10 minutes?", "", 3.4057, new double[] { -2.4671, -2.1218, -1.6581, -1.1352 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFB33", "", "Are you able to remove something from your back pocket?", "", 2.57454, new double[] { -3.5227, -2.911, -2.3783, -1.7469 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFB34", "", "Are you able to change a light bulb overhead?", "", 3.14216, new double[] { -2.3684, -1.9837, -1.5693, -0.9182 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFB36", "", "Are you able to put on a pullover sweater?", "", 2.48332, new double[] { -3.7792, -3.1182, -2.2895, -1.5101 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFB39r1", "", "Are you able to reach and get down a 5 pound (2 kg) object from above your head?", "", 2.74, new double[] { -2.61, -2.1, -1.63, -0.94 }, -1, "",
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFB40", "", "Are you able to stand up on tiptoes?", "", 3.02053, new double[] { -2.2796, -1.9146, -1.5496, -0.9773 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFB41", "", "Are you able to trim your fingernails?", "", 2.08802, new double[] { -3.6609, -3.1676, -2.6151, -2.0231 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFB42", "", "Are you able to stand unsupported for 30 minutes?", "", 3.09148, new double[] { -2.0133, -1.6581, -1.2635, -0.7208 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFB43", "", "Does your health now limit you in taking care of your personal needs (dress, comb hair, toilet, eat, bathe)?", "", 3.0408, new double[] { -3.5622, -2.546, -1.885, -1.3029 }, -1, "", 
    response("Not at all", 5),
    response("Very little", 4),
    response("Somewhat", 3),
    response("Quite a lot", 2),
    response("Cannot do", 1)
  ),
  item("PFB44", "", "Does your health now limit you in doing moderate activities, such as moving a table, pushing a vacuum cleaner, bowling, or playing golf?", "", 4.27739, new double[] { -2.1119, -1.4706, -0.8984, -0.4249 }, -1, "", 
    response("Not at all", 5),
    response("Very little", 4),
    response("Somewhat", 3),
    response("Quite a lot", 2),
    response("Cannot do", 1)
  ),
  item("PFB48", "", "Does your health now limit you in taking a shower?", "", 3.42597, new double[] { -3.2169, -2.4276, -1.8455, -1.3621 }, -1, "", 
    response("Not at all", 5),
    response("Very little", 4),
    response("Somewhat", 3),
    response("Quite a lot", 2),
    response("Cannot do", 1)
  ),
  item("PFB49", "", "Does your health now limit you in going for a short walk (less than 15 minutes)?", "", 3.57801, new double[] { -2.1908, -1.6778, -1.1845, -0.7406 }, -1, "", 
    response("Not at all", 5),
    response("Very little", 4),
    response("Somewhat", 3),
    response("Quite a lot", 2),
    response("Cannot do", 1)
  ),
  item("PFB50", "", "How much difficulty do you have doing your daily physical activities, because of your health?", "", 4.23685, new double[] { -2.7532, -1.8061, -1.1451, -0.3163 }, -1, "", 
    response("No difficulty at all", 5),
    response("A little bit of difficulty", 4),
    response("Some difficulty", 3),
    response("A lot of difficulty", 2),
    response("Can't do because of health", 1)
  ),
  item("PFB51", "", "Does your health now limit you in participating in active sports such as swimming, tennis, or basketball?", "", 3.16243, new double[] { -1.2931, -0.6912, -0.1388, 0.2657 }, -1, "", 
    response("Not at all", 5),
    response("Very little", 4),
    response("Somewhat", 3),
    response("Quite a lot", 2),
    response("Cannot do", 1)
  ),
  item("PFB54", "", "Does your health now limit you in going OUTSIDE the home, for example to shop or visit a doctor's office?", "", 3.39556, new double[] { -3.286, -2.2698, -1.6877, -1.1944 }, -1, "",
    response("Not at all", 5),
    response("Very little", 4),
    response("Somewhat", 3),
    response("Quite a lot", 2),
    response("Cannot do", 1)
  ),
  item("PFB56r1", "", "Are you able to lift one pound (0.5 kg) to shoulder level without bending your elbow?", "", 2.29, new double[] { -2.9, -2.44, -1.98, -1.38 }, -1, "",
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFB5r1", "", "Does your health now limit you in hiking a couple of miles (3 km) on uneven surfaces, including hills?", "", 4.37, new double[] { -1.10,  -0.69, -0.21, 0.24 }, -1, "",
    response("Not at all", 5),
    response("Very little", 4),
    response("Somewhat", 3),
    response("Quite a lot", 2),
    response("Cannot do", 1)
  ),
  item("PFB7", "", "Does your health now limit you in doing strenuous activities such as backpacking, skiing, playing tennis, bicycling or jogging?", "", 4.22671, new double[] { -0.9182, -0.4347, 0.0487, 0.4729 }, -1, "", 
    response("Not at all", 5),
    response("Very little", 4),
    response("Somewhat", 3),
    response("Quite a lot", 2),
    response("Cannot do", 1)
  ),
  item("PFB8r1", "", "Are you able to carry two bags filled with groceries 100 yards (100 m)?", "", 3.68, new double[] { -1.79, -1.4, -0.9, -0.3 }, -1, "",
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFB9", "", "Are you able to jump up and down?", "", 3.58814, new double[] { -1.6482, -1.2832, -0.8787, -0.3657 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFC10", "", "Does your health now limit you in climbing several flights of stairs?", "", 4.1963, new double[] { -1.8061, -1.1451, -0.563, -0.1092 }, -1, "", 
    response("Not at all", 5),
    response("Very little", 4),
    response("Somewhat", 3),
    response("Quite a lot", 2),
    response("Cannot do", 1)
  ),
  item("PFC12", "", "Does your health now limit you in doing two hours of physical labor?", "", 4.68283, new double[] { -1.4213, -0.9182, -0.3854, 0.0586 }, -1, "", 
    response("Not at all", 5),
    response("Very little", 4),
    response("Somewhat", 3),
    response("Quite a lot", 2),
    response("Cannot do", 1)
  ),
  item("PFC13r1", "", "Are you able to run 100 yards (100 m)?", "", 3.2, new double[] { -0.83, -0.54, -0.14, 0.5 }, -1, "",
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFC29", "", "Are you able to walk up and down two steps?", "", 3.20298, new double[] { -2.8913, -2.3586, -1.7962, -1.1648 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFC31", "", "Are you able to reach into a low cupboard?", "", 2.50359, new double[] { -3.1182, -2.2698, -1.5989, -0.8392 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFC32", "", "Are you able to climb up 5 flights of stairs?", "", 3.55774, new double[] { -1.5594, -0.9675, -0.4347, 0.246 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFC33r1", "", "Are you able to run ten miles (16 km)?", "", 2.02, new double[] { 0.28, 0.97, 1.67, 2.24 }, -1, "",
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFC35", "", "Does your health now limit you in doing eight hours of physical labor?", "", 3.02053, new double[] { -1.0957, -0.5926, 0.0092, 0.4828 }, -1, "", 
    response("Not at all", 5),
    response("Very little", 4),
    response("Somewhat", 3),
    response("Quite a lot", 2),
    response("Cannot do", 1)
  ),
  item("PFC36r1", "", "Does your health now limit you in walking more than a mile (1.6 km)?", "", 4.46, new double[] { -1.43, -1.01, -0.59, -0.23 }, -1, "",
    response("Not at all", 5),
    response("Very little", 4),
    response("Somewhat", 3),
    response("Quite a lot", 2),
    response("Cannot do", 1)
  ),
  item("PFC37", "", "Does your health now limit you in climbing one flight of stairs?", "", 4.45984, new double[] { -2.3092, -1.6285, -1.0464, -0.5728 }, -1, "", 
    response("Not at all", 5),
    response("Very little", 4),
    response("Somewhat", 3),
    response("Quite a lot", 2),
    response("Cannot do", 1)
  ),
  item("PFC38", "", "Are you able to walk at a normal speed?", "", 4.33821, new double[] { -2.0429, -1.6877, -1.224, -0.711 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFC39", "", "Are you able to stand without losing your balance for several minutes?", "", 2.68604, new double[] { -2.5953, -2.1711, -1.7173, -1.1549 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFC40", "", "Are you able to kneel on the floor?", "", 2.87862, new double[] { -1.8949, -1.3522, -0.8984, -0.2078 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFC41", "", "Are you able to sit down in and stand up from a low, soft couch?", "", 3.22325, new double[] { -2.6052, -1.6877, -1.1352, -0.267 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFC43", "", "Are you able to use your hands, such as for turning faucets, using kitchen gadgets, or sewing?", "", 2.04747, new double[] { -3.9963, -3.0393, -2.1711, -1.3917 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFC45r1", "", "Are you able to sit on and get up from the toilet?", "", 3.11, new double[] { -3.11, -2.78, -2.21, -1.46 }, -1, "",
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFC46", "", "Are you able to transfer from a bed to a chair and back?", "", 3.47665, new double[] { -3.3649, -2.8617, -2.2796, -1.5496 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFC47", "", "Are you able to be out of bed most of the day?", "", 2.30087, new double[] { -3.6806, -3.0985, -2.3783, -1.6877 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFC49", "", "Are you able to water a house plant?", "", 3.17257, new double[] { -3.0689, -2.8519, -2.4276, -1.8949 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFC51", "", "Are you able to wipe yourself after using the toilet?", "", 2.35155, new double[] { -3.651, -2.9998, -2.4276, -1.668 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFC52", "", "Are you able to turn from side to side in bed?", "", 2.46305, new double[] { -3.5523, -2.7039, -2.0823, -1.2043 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFC53", "", "Are you able to get in and out of bed?", "", 2.87862, new double[] { -3.5326, -2.7236, -2.0725, -1.1845 }, -1, "", 
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFC54", "", "Does your health now limit you in getting in and out of the bathtub?", "", 2.80767, new double[] { -2.4079, -1.9738, -1.4114, -0.928 }, -1, "", 
    response("Not at all", 5),
    response("Very little", 4),
    response("Somewhat", 3),
    response("Quite a lot", 2),
    response("Cannot do", 1)
  ),
  item("PFC56", "", "Does your health now limit you in walking about the house?", "", 4.12535, new double[] { -2.8519, -2.3783, -1.6581, -1.1352 }, -1, "", 
    response("Not at all", 5),
    response("Very little", 4),
    response("Somewhat", 3),
    response("Quite a lot", 2),
    response("Cannot do", 1)
  ),
  item("PFC6r1", "", "Are you able to walk a block (about 100 m) on flat ground?", "", 3.93, new double[] {  -2.34, -1.84, -1.38, -0.9 }, -1, "",
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  ),
  item("PFC7r1", "", "Are you able to run five miles (8 km)?", "", 2.43, new double[] {  0.07, 0.53, 1.14, 1.77 }, -1, "",
    response("Without any difficulty", 5),
    response("With a little difficulty", 4),
    response("With some difficulty", 3),
    response("With much difficulty", 2),
    response("Unable to do", 1)
  )
);

  public static ItemBank bank() {
    return bank;
  }
}