/*
 * Copyright 2018 The Board of Trustees of The Leland Stanford Junior University.
 * All Rights Reserved.
 *
 * See the NOTICE and LICENSE files distributed with this work for information
 * regarding copyright ownership and licensing. You may not use this file except
 * in compliance with a written license agreement with Stanford University.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See your
 * License for the specific language governing permissions and limitations under
 * the License.
 */

package edu.stanford.survey.server.promis;

import edu.stanford.survey.server.CatAlgorithm.ItemBank;

import static edu.stanford.survey.server.ItemBanks.*;

/**
 * Item bank for PROMIS assessment. Generated from OID 0E6A8A9B-B053-43BA-887F-CDDBD85FCB49.
 */
public class PromisParentProxyBankOneZeroPainBehavior {
  private static final ItemBank bank = itemBank(0.0, 0.0, 5, 12, 4.0,
      item("PAINBE13_PROX", "In the past 7 days, when my child was in pain", "he/she tried not to move.", "", 3.48, new double[] { -2.62, -0.48, -0.06, 0.73, 1.42 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PAINBE16_PROX", "In the past 7 days, when my child was in pain", "his/her face looked sad.", "", 3.04, new double[] { -2.22, -0.88, -0.32, 0.46, 1.19 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PAINBE18_PROX", "In the past 7 days, when my child was in pain", "he/she asked for help with doing things.", "", 2.92, new double[] { -2.87, -0.63, -0.04, 0.87, 1.56 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PAINBE23_PROX", "In the past 7 days, when my child was in pain", "he/she asked people to let him/her be by him-/her-self.", "", 2.29, new double[] { -2.91, -0.43, 0.25, 1.17, 1.87 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PAINBE24_PROX", "In the past 7 days, when my child was in pain", "he/she moved stiffly.", "", 2.44, new double[] { -2.53, -1.13, -0.59, 0.56, 1.04 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PAINBE25_PROX", "In the past 7 days, when my child was in pain", "he/she yelled for someone to help him/her.", "", 2.51, new double[] { -2.67, 0.02, 0.59, 1.26, 1.84 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PAINBE27_PROX", "In the past 7 days, when my child was in pain", "he/she cried.", "", 2.72, new double[] { -2.47, -0.41, 0.11, 1.12, 1.78 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PAINBE29_PROX", "In the past 7 days, when my child was in pain", "he/she used something for support (cane, crutches, wheelchair) to move from place to place.", "", 2.09, new double[] { -2.95, 0.91, 1.24, 1.85, 2.17 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PAINBE31_PROX", "In the past 7 days, when my child was in pain", "he/she limped.", "", 1.89, new double[] { -2.73, -0.54, -0.13, 0.94, 1.41 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PAINBE32_PROX", "In the past 7 days, when my child was in pain", "he/she became quiet.", "", 2.12, new double[] { -2.82, -0.85, -0.24, 0.7, 1.28 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PAINBE34_PROX", "In the past 7 days, when my child was in pain", "he/she asked for help getting around.", "", 2.66, new double[] { -2.2, 0.07, 0.67, 1.42, 1.82 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PAINBE35_PROX", "In the past 7 days, when my child was in pain", "he/she groaned.", "", 2.38, new double[] { -2.55, -0.56, 0.1, 0.84, 1.69 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PAINBE37_PROX", "In the past 7 days, when my child was in pain", "he/she stayed away from other people.", "", 2.84, new double[] { -2.52, -0.41, 0.13, 0.92, 1.57 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PAINBE41_PROX", "In the past 7 days, when my child was in pain", "he/she screamed.", "", 2.37, new double[] { -2.85, 0.37, 0.85, 1.54, 1.89 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PAINBE46_PROX", "In the past 7 days, when my child was in pain", "he/she protected the part of his/her body that hurt.", "", 2.34, new double[] { -2.71, -1.02, -0.5, 0.53, 1.21 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PAINBE48_PROX", "In the past 7 days, when my child was in pain", "he/she tightened his/her jaw.", "", 1.98, new double[] { -2.83, 0.03, 0.58, 1.53, 2.43 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PAINBE4_PROX", "In the past 7 days, when my child was in pain", "he/she asked for medicine.", "", 1.98, new double[] { -2.83, -0.92, -0.43, 0.7, 1.32 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PAINBE51_PROX", "In the past 7 days, when my child was in pain", "he/she didn't let anyone touch him/her.", "", 2.42, new double[] { -2.59, -0.28, 0.2, 1.02, 1.7 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PAINBE5_PROX", "In the past 7 days, when my child was in pain", "he/she talked about his/her pain.", "", 2.28, new double[] { -2.77, -1.3, -0.61, 0.52, 1.28 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PAINBE7_PROX", "In the past 7 days, when my child was in pain", "he/she rubbed his/her body where it hurt.", "", 2.12, new double[] { -2.71, -0.97, -0.59, 0.44, 1.08 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PAINBE8_PROX", "In the past 7 days, when my child was in pain", "he/she moved slower.", "", 2.59, new double[] { -3.01, -1.3, -0.81, 0.33, 1.0 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PAINBE9_PROX", "In the past 7 days, when my child was in pain", "he/she got angry at people.", "", 1.9, new double[] { -2.97, -0.61, -0.05, 1.07, 1.91 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW13_PROX", "In the past 7 days, when my child was in pain", "he/she sighed.", "", 2.48, new double[] { -2.57, -0.64, -0.17, 0.88, 1.45 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW14_PROX", "In the past 7 days, when my child was in pain", "he/she took breaks from what he/she was doing.", "", 2.83, new double[] { -2.27, -0.98, -0.49, 0.5, 1.14 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW18_PROX", "In the past 7 days, when my child was in pain", "he/she told people he/she couldn't do his/her usual chores.", "", 2.98, new double[] { -2.67, -0.4, 0.03, 0.74, 1.39 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW21_PROX", "In the past 7 days, when my child was in pain", "he/she told people he/she couldn't do things with them.", "", 3.17, new double[] { -2.65, -0.38, 0.11, 0.92, 1.64 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW24_PROX", "In the past 7 days, when my child was in pain", "he/she asked for someone to help him/her.", "", 2.81, new double[] { -2.53, -0.65, -0.16, 0.91, 1.23 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW2_PROX", "In the past 7 days, when my child was in pain", "it showed on his/her face.", "", 2.94, new double[] { -2.68, -1.11, -0.64, 0.33, 1.07 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW32_PROX", "In the past 7 days, when my child was in pain", "he/she lay down.", "", 2.62, new double[] { -2.53, -1.22, -0.78, 0.37, 0.86 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW4_PROX", "In the past 7 days, when my child was in pain", "he/she felt his/her body get tense.", "", 2.65, new double[] { -2.73, -0.68, -0.21, 0.72, 1.42 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW_PROX", "In the past 7 days, when my child was in pain", "he/she didn't want anyone to touch him/her.", "", 2.25, new double[] { -2.65, -0.42, 0.18, 0.98, 1.5 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW_PROX1", "In the past 7 days, when my child was in pain", "he/she avoided standing.", "", 2.53, new double[] { -2.39, -0.52, -0.05, 0.88, 1.68 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW_PROX10", "In the past 7 days, when my child was in pain", "he/she asked people to bring him/her things (food, games).", "", 2.9, new double[] { -2.51, -0.54, -0.07, 0.78, 1.4 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW_PROX11", "In the past 7 days, when my child was in pain", "he/she couldn't stay still.", "", 1.79, new double[] { -2.69, -0.24, 0.43, 1.54, 2.38 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW_PROX12", "In the past 7 days, when my child was in pain", "he/she was restless.", "", 2.34, new double[] { -2.71, -0.77, -0.28, 0.67, 1.3 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW_PROX13", "In the past 7 days, when my child was in pain", "he/she tried to think of something nice/fun.", "", 1.51, new double[] { -3.01, -0.98, -0.36, 1.26, 2.17 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW_PROX14", "In the past 7 days, when my child was in pain", "he/she went to sleep.", "", 1.72, new double[] { -2.9, -0.92, -0.23, 0.77, 1.5 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW_PROX15", "In the past 7 days, when my child was in pain", "he/she had to stop what he/she was doing.", "", 3.02, new double[] { -2.34, -0.76, -0.27, 0.85, 1.4 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW_PROX2", "In the past 7 days, when my child was in pain", "he/she avoided lifting or carrying heavy things.", "", 2.43, new double[] { -2.7, -0.66, -0.26, 0.49, 1.2 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW_PROX3", "In the past 7 days, when my child was in pain", "he/she stayed near to someone who cares about him/her.", "", 2.17, new double[] { -2.88, -1.17, -0.67, 0.19, 0.87 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW_PROX4", "In the past 7 days, when my child was in pain", "he/she tried to rest or relax.", "", 2.48, new double[] { -3.02, -1.52, -1.01, 0.17, 0.93 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW_PROX5", "In the past 7 days, when my child was in pain", "he/she complained.", "", 2.2, new double[] { -2.69, -1.32, -0.54, 0.49, 1.28 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW_PROX6", "In the past 7 days, when my child was in pain", "he/she asked to see a doctor.", "", 2.0, new double[] { -2.82, 0.04, 0.54, 1.37, 2.17 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW_PROX7", "In the past 7 days, when my child was in pain", "he/she pulled away if someone touched him/her where it hurt.", "", 2.7, new double[] { -2.41, -0.44, 0.07, 0.7, 1.16 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW_PROX8", "In the past 7 days, when my child was in pain", "he/she argued with people.", "", 1.9, new double[] { -2.73, -0.68, -0.1, 0.99, 1.92 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW_PROX9", "In the past 7 days, when my child was in pain", "he/she avoided using the part of his/her body that hurt.", "", 2.57, new double[] { -2.57, -1.08, -0.58, 0.48, 1.22 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW_PROXA", "In the past 7 days, when my child was in pain", "he/she said mean words to people.", "", 1.78, new double[] { -2.78, -0.52, 0.16, 1.24, 1.99 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW_PROXB", "In the past 7 days, when my child was in pain", "he/she got mad and threw or hit something.", "", 1.87, new double[] { -2.89, 0.44, 1.08, 2.21, 2.72 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW_PROXC", "In the past 7 days, when my child was in pain", "he/she had a fixed or dazed expression.", "", 2.28, new double[] { -2.9, -0.09, 0.47, 1.59, 2.02 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW_PROXD", "In the past 7 days, when my child was in pain", "he/she had tears in his/her eyes.", "", 3.0, new double[] { -2.12, -0.43, 0.03, 0.93, 1.51 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW_PROXE", "In the past 7 days, when my child was in pain", "he/she had circles under his/her eyes.", "", 1.59, new double[] { -2.61, -0.14, 0.44, 1.5, 2.35 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      )
  );

  public static ItemBank bank() {
    return bank;
  }
}
