/*
 * Copyright 2018 The Board of Trustees of The Leland Stanford Junior University.
 * All Rights Reserved.
 *
 * See the NOTICE and LICENSE files distributed with this work for information
 * regarding copyright ownership and licensing. You may not use this file except
 * in compliance with a written license agreement with Stanford University.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See your
 * License for the specific language governing permissions and limitations under
 * the License.
 */

package edu.stanford.survey.server.promis;

import edu.stanford.survey.server.CatAlgorithm.ItemBank;

import static edu.stanford.survey.server.ItemBanks.*;

/**
 * Item bank for PROMIS assessment. Generated from OID A39DF042-47FE-4987-9696-8CBA1747EEFF.
 */
public class PromisPedBankOneZeroPainBehavior {
  private static final ItemBank bank = itemBank(0.0, 0.0, 5, 12, 4.0,
      item("PAINBE13_Ped", "In the past 7 days, when I was in pain", "I tried not to move.", "", 3.66, new double[] { -1.39, -0.13, 0.18, 0.67, 1.05 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PAINBE18_Ped", "In the past 7 days, when I was in pain", "I asked for help with doing things.", "", 3.66, new double[] { -1.51, -0.17, 0.2, 0.73, 1.12 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PAINBE23_Ped", "In the past 7 days, when I was in pain", "I asked people to let me be by myself.", "", 2.84, new double[] { -1.56, 0.13, 0.41, 0.95, 1.41 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PAINBE24_Ped", "In the past 7 days, when I was in pain", "I moved stiffly.", "", 2.74, new double[] { -1.82, -0.49, -0.09, 0.48, 0.99 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PAINBE25_Ped", "In the past 7 days, when I was in pain", "I yelled for someone to help me.", "", 3.76, new double[] { -1.36, 0.35, 0.67, 1.04, 1.25 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PAINBE27_Ped", "In the past 7 days, when I was in pain", "I cried.", "", 3.55, new double[] { -1.42, 0.03, 0.32, 0.76, 1.07 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PAINBE29_Ped", "In the past 7 days, when I was in pain", "I used something for support (cane, crutches, wheelchair) to move from place to place.", "", 2.85, new double[] { -1.44, 0.76, 0.99, 1.38, 1.55 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PAINBE31_Ped", "In the past 7 days, when I was in pain", "I limped.", "", 2.7, new double[] { -1.6, -0.12, 0.18, 0.69, 1.07 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PAINBE32_Ped", "In the past 7 days, when I was in pain", "I became quiet.", "", 2.65, new double[] { -1.55, -0.22, 0.09, 0.68, 1.16 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PAINBE34_Ped", "In the past 7 days, when I was in pain", "I asked for help getting around.", "", 4.01, new double[] { -1.19, 0.25, 0.55, 0.89, 1.15 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PAINBE35_Ped", "In the past 7 days, when I was in pain", "I groaned.", "", 3.49, new double[] { -1.5, -0.12, 0.27, 0.82, 1.2 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PAINBE37_Ped", "In the past 7 days, when I was in pain", "I stayed away from other people.", "", 3.4, new double[] { -1.71, 0.08, 0.39, 0.89, 1.26 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PAINBE41_Ped", "In the past 7 days, when I was in pain", "I screamed.", "", 3.65, new double[] { -1.37, 0.42, 0.77, 1.12, 1.35 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PAINBE46_Ped", "In the past 7 days, when I was in pain", "I protected the part of my body that hurt.", "", 3.55, new double[] { -1.46, -0.32, -0.03, 0.47, 0.83 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PAINBE48_Ped", "In the past 7 days, when I was in pain", "I tightened my jaw.", "", 2.42, new double[] { -1.5, 0.12, 0.46, 0.98, 1.49 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PAINBE4_Ped", "In the past 7 days, when I was in pain", "I asked for medicine.", "", 2.65, new double[] { -1.75, -0.27, 0.01, 0.65, 1.13 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PAINBE51_Ped", "In the past 7 days, when I was in pain", "I didn't let anyone touch me.", "", 2.89, new double[] { -1.45, -0.02, 0.33, 0.8, 1.15 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PAINBE5_Ped", "In the past 7 days, when I was in pain", "I talked about my pain.", "", 2.22, new double[] { -1.93, -0.47, 0.06, 0.8, 1.29 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PAINBE7_Ped", "In the past 7 days, when I was in pain", "I rubbed my body where it hurt.", "", 1.81, new double[] { -2.02, -0.73, -0.33, 0.39, 1.06 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PAINBE8_Ped", "In the past 7 days, when I was in pain", "I moved slower.", "", 4.39, new double[] { -1.41, -0.46, -0.17, 0.37, 0.74 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PAINBE9_Ped", "In the past 7 days, when I was in pain", "I got angry at people.", "", 2.88, new double[] { -1.54, 0.05, 0.38, 0.91, 1.27 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW13_Ped", "In the past 7 days, when I was in pain", "I sighed.", "", 2.86, new double[] { -1.81, -0.22, 0.09, 0.66, 1.12 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW14_Ped", "In the past 7 days, when I was in pain", "I took breaks from what I was doing.", "", 3.91, new double[] { -1.59, -0.4, -0.16, 0.49, 0.97 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW18_Ped", "In the past 7 days, when I was in pain", "I told people I couldn't do my usual chores.", "", 3.81, new double[] { -1.28, 0.09, 0.41, 0.82, 1.22 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW21_Ped", "In the past 7 days, when I was in pain", "I told people I couldn't do things with them.", "", 3.58, new double[] { -1.33, -0.07, 0.25, 0.75, 1.12 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW24_Ped", "In the past 7 days, when I was in pain", "I asked for someone to help me.", "", 3.65, new double[] { -1.41, -0.14, 0.23, 0.73, 1.04 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW2_Ped", "In the past 7 days, when I was in pain", "it showed on my face.", "", 3.44, new double[] { -1.44, -0.29, 0.0, 0.52, 0.89 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW32_Ped", "In the past 7 days, when I was in pain", "I lay down.", "", 3.26, new double[] { -1.41, -0.6, -0.25, 0.33, 0.89 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW4_Ped", "In the past 7 days, when I was in pain", "I felt my body get tense.", "", 3.26, new double[] { -1.47, -0.2, 0.08, 0.6, 1.06 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW_Ped", "In the past 7 days, when I was in pain", "I didn't want anyone to touch me.", "", 3.27, new double[] { -1.54, -0.07, 0.17, 0.58, 0.96 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW_Ped1", "In the past 7 days, when I was in pain", "I avoided standing.", "", 3.55, new double[] { -1.81, -0.19, 0.14, 0.65, 1.01 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW_Ped10", "In the past 7 days, when I was in pain", "I asked people to bring me things (food, games).", "", 3.51, new double[] { -1.47, -0.09, 0.21, 0.71, 1.03 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW_Ped11", "In the past 7 days, when I was in pain", "I couldn't stay still.", "", 2.67, new double[] { -1.66, -0.21, 0.11, 0.71, 1.27 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW_Ped12", "In the past 7 days, when I was in pain", "I was restless.", "", 3.0, new double[] { -1.6, -0.26, 0.02, 0.54, 1.02 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW_Ped13", "In the past 7 days, when I was in pain", "I tried to think of something nice/fun.", "", 2.17, new double[] { -1.79, -0.46, -0.05, 0.72, 1.28 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW_Ped14", "In the past 7 days, when I was in pain", "I went to sleep.", "", 2.38, new double[] { -1.68, -0.36, 0.05, 0.6, 1.14 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW_Ped15", "In the past 7 days, when I was in pain", "I had to stop what I was doing.", "", 4.58, new double[] { -1.26, -0.32, 0.03, 0.62, 0.99 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW_Ped2", "In the past 7 days, when I was in pain", "I avoided lifting or carrying heavy things.", "", 3.4, new double[] { -1.57, -0.22, 0.04, 0.45, 0.87 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW_Ped3", "In the past 7 days, when I was in pain", "I stayed near to someone who cares about me.", "", 2.52, new double[] { -1.82, -0.59, -0.23, 0.34, 0.85 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW_Ped4", "In the past 7 days, when I was in pain", "I tried to rest or relax.", "", 2.65, new double[] { -1.79, -0.91, -0.62, 0.22, 0.85 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW_Ped5", "In the past 7 days, when I was in pain", "I complained.", "", 3.09, new double[] { -1.67, -0.48, -0.06, 0.51, 0.92 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW_Ped6", "In the past 7 days, when I was in pain", "I asked to see a doctor.", "", 2.49, new double[] { -1.64, 0.27, 0.54, 1.16, 1.56 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW_Ped7", "In the past 7 days, when I was in pain", "I pulled away if someone touched me where it hurt.", "", 3.31, new double[] { -1.53, -0.19, 0.09, 0.51, 0.9 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW_Ped8", "In the past 7 days, when I was in pain", "I argued with people.", "", 2.56, new double[] { -1.61, 0.07, 0.38, 0.96, 1.54 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW_Ped9", "In the past 7 days, when I was in pain", "I avoided using the part of my body that hurt.", "", 3.51, new double[] { -1.67, -0.39, -0.06, 0.41, 0.86 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW_PedA", "In the past 7 days, when I was in pain", "I said mean words to people.", "", 2.36, new double[] { -1.8, 0.31, 0.64, 1.23, 1.76 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      ),
      item("PBNEW_PedB", "In the past 7 days, when I was in pain", "I got mad and threw or hit something.", "", 2.19, new double[] { -1.72, 0.58, 1.02, 1.59, 1.95 }, -1, "",
          response("Had No Pain", 1),
          response("Never", 2),
          response("Almost Never", 3),
          response("Sometimes", 4),
          response("Often", 5),
          response("Almost Always", 6)
      )
  );

  public static ItemBank bank() {
    return bank;
  }
}
