/*
 * Copyright 2013 The Board of Trustees of The Leland Stanford Junior University.
 * All Rights Reserved.
 *
 * See the NOTICE and LICENSE files distributed with this work for information
 * regarding copyright ownership and licensing. You may not use this file except
 * in compliance with a written license agreement with Stanford University.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See your
 * License for the specific language governing permissions and limitations under
 * the License.
 */

package edu.stanford.survey.server.promis;

import edu.stanford.survey.server.CatAlgorithm.ItemBank;

import static edu.stanford.survey.server.ItemBanks.*;

/**
 * Item bank for PROMIS fatigue assessment. Generated from OID B3B30AF1-7536-451D-AD39-62A097A5EA4D.
 */
public class PromisFatigue2 {
  private static final ItemBank bank = itemBank(0.0, 0.0, 4, 12, 3.0,
      item("AN1", "During the past 7 days:", "I feel listless (\"washed out\")", "", 3.26908, new double[] { -0.2029, 0.7442, 1.3736, 2.2719 }, -1, "",
          response("Not at all", 1),
          response("A little bit", 2),
          response("Somewhat", 3),
          response("Quite a bit", 4),
          response("Very much", 5)
      ),
      item("An12", "During the past 7 days:", "I am too tired to eat", "", 2.31351, new double[] { 0.9482, 1.72, 2.4746, 3.5385 }, -1, "",
          response("Not at all", 1),
          response("A little bit", 2),
          response("Somewhat", 3),
          response("Quite a bit", 4),
          response("Very much", 5)
      ),
      item("An14", "During the past 7 days:", "I need help doing my usual activities", "", 2.3058, new double[] { 0.753, 1.521, 2.1999, 3.0206 }, -1, "",
          response("Not at all", 1),
          response("A little bit", 2),
          response("Somewhat", 3),
          response("Quite a bit", 4),
          response("Very much", 5)
      ),
      item("An15", "During the past 7 days:", "I am frustrated by being too tired to do the things I want to do", "", 3.89913, new double[] { -0.0878, 0.6132, 1.0693, 1.431 }, -1, "",
          response("Not at all", 1),
          response("A little bit", 2),
          response("Somewhat", 3),
          response("Quite a bit", 4),
          response("Very much", 5)
      ),
      item("An16", "During the past 7 days:", "I have to limit my social activity because I am tired", "", 3.60561, new double[] { 0.1475, 0.8289, 1.418, 1.8725 }, -1, "",
          response("Not at all", 1),
          response("A little bit", 2),
          response("Somewhat", 3),
          response("Quite a bit", 4),
          response("Very much", 5)
      ),
      item("An2", "During the past 7 days:", "I feel tired", "", 3.30015, new double[] { -1.3566, 0.0993, 0.8436, 1.8003 }, -1, "",
          response("Not at all", 1),
          response("A little bit", 2),
          response("Somewhat", 3),
          response("Quite a bit", 4),
          response("Very much", 5)
      ),
      item("An3", "During the past 7 days:", "I have trouble <u>starting</u> things because I am tired", "", 4.34709, new double[] { -0.3111, 0.5041, 1.1796, 1.9585 }, -1, "",
          response("Not at all", 1),
          response("A little bit", 2),
          response("Somewhat", 3),
          response("Quite a bit", 4),
          response("Very much", 5)
      ),
      item("An4", "During the past 7 days:", "I have trouble <u>finishing</u> things because I am tired", "", 3.40335, new double[] { -0.3408, 0.5818, 1.2795, 2.1366 }, -1, "",
          response("Not at all", 1),
          response("A little bit", 2),
          response("Somewhat", 3),
          response("Quite a bit", 4),
          response("Very much", 5)
      ),
      item("An5", "During the past 7 days:", "I have energy", "", 2.71096, new double[] { -1.3865, 0.0032, 1.0096, 2.1717 }, -1, "",
          response("Not at all", 5),
          response("A little bit", 4),
          response("Somewhat", 3),
          response("Quite a bit", 2),
          response("Very much", 1)
      ),
      item("An7", "During the past 7 days:", "I am able to do my usual activities", "", 2.55435, new double[] { -0.4984, 0.597, 1.68, 2.5963 }, -1, "",
          response("Not at all", 5),
          response("A little bit", 4),
          response("Somewhat", 3),
          response("Quite a bit", 2),
          response("Very much", 1)
      ),
      item("An8", "During the past 7 days:", "I need to sleep during the day", "", 1.64286, new double[] { -0.4334, 0.8737, 1.5607, 2.5179 }, -1, "",
          response("Not at all", 1),
          response("A little bit", 2),
          response("Somewhat", 3),
          response("Quite a bit", 4),
          response("Very much", 5)
      ),
      item("FATEXP12", "In the past 7 days", "To what degree did you feel tired even when you hadn't done anything?", "", 2.96129, new double[] { -0.568, 0.4993, 1.2739, 2.2954 }, -1, "",
          response("Not at all", 1),
          response("A little bit", 2),
          response("Somewhat", 3),
          response("Quite a bit", 4),
          response("Very much", 5)
      ),
      item("FATEXP13", "In the past 7 days", "How bushed were you on average?", "", 3.35857, new double[] { -0.7174, 0.4251, 1.2403, 2.261 }, -1, "",
          response("Not at all", 1),
          response("A little bit", 2),
          response("Somewhat", 3),
          response("Quite a bit", 4),
          response("Very much", 5)
      ),
      item("FATEXP16", "In the past 7 days", "How often were you sluggish?", "", 2.65053, new double[] { -1.2739, -0.0589, 1.091, 2.2697 }, -1, "",
          response("Never", 1),
          response("Rarely", 2),
          response("Sometimes", 3),
          response("Often", 4),
          response("Always", 5)
      ),
      item("FATEXP18", "In the past 7 days", "How often did you run out of energy?", "", 3.38925, new double[] { -1.0135, 0.0387, 1.0796, 2.1624 }, -1, "",
          response("Never", 1),
          response("Rarely", 2),
          response("Sometimes", 3),
          response("Often", 4),
          response("Always", 5)
      ),
      item("FATEXP19", "In the past 7 days", "How often were you physically drained?", "", 3.65446, new double[] { -0.788, 0.1715, 1.1299, 2.1994 }, -1, "",
          response("Never", 1),
          response("Rarely", 2),
          response("Sometimes", 3),
          response("Often", 4),
          response("Always", 5)
      ),
      item("FATEXP2", "In the past 7 days", "How often did you feel run-down?", "", 3.42126, new double[] { -0.916, 0.0375, 1.009, 2.0319 }, -1, "",
          response("Never", 1),
          response("Rarely", 2),
          response("Sometimes", 3),
          response("Often", 4),
          response("Always", 5)
      ),
      item("FATEXP20", "In the past 7 days", "How often did you feel tired?", "", 3.25088, new double[] { -1.6209, -0.4778, 0.7291, 1.7908 }, -1, "",
          response("Never", 1),
          response("Rarely", 2),
          response("Sometimes", 3),
          response("Often", 4),
          response("Always", 5)
      ),
      item("FATEXP21", "In the past 7 days", "How fatigued were you when your fatigue was at its worst?", "", 2.82861, new double[] { -1.4322, -0.3883, 0.398, 1.3267 }, -1, "",
          response("Not at all", 1),
          response("A little bit", 2),
          response("Somewhat", 3),
          response("Quite a bit", 4),
          response("Very much", 5)
      ),
      item("FATEXP22", "In the past 7 days", "How often were you bothered by your fatigue?", "", 3.89996, new double[] { -0.81, 0.1248, 0.9957, 1.8786 }, -1, "",
          response("Never", 1),
          response("Rarely", 2),
          response("Sometimes", 3),
          response("Often", 4),
          response("Always", 5)
      ),
      item("FATEXP24", "In the past 7 days", "How often did you have enough energy to enjoy the things you do for fun?", "", 2.10594, new double[] { -0.6373, 0.5112, 1.5269, 2.4256 }, -1, "",
          response("Never", 5),
          response("Rarely", 4),
          response("Sometimes", 3),
          response("Often", 2),
          response("Always", 1)
      ),
      item("FATEXP26", "In the past 7 days", "How often were you too tired to enjoy life?", "", 3.19291, new double[] { -0.3262, 0.5795, 1.3791, 2.3377 }, -1, "",
          response("Never", 1),
          response("Rarely", 2),
          response("Sometimes", 3),
          response("Often", 4),
          response("Always", 5)
      ),
      item("FATEXP28", "In the past 7 days", "How often were you too tired to feel happy?", "", 3.04369, new double[] { -0.1061, 0.7465, 1.5562, 2.5225 }, -1, "",
          response("Never", 1),
          response("Rarely", 2),
          response("Sometimes", 3),
          response("Often", 4),
          response("Always", 5)
      ),
      item("FATEXP29", "In the past 7 days", "How often did you feel totally drained?", "", 3.09404, new double[] { -0.5715, 0.293, 1.2404, 2.2878 }, -1, "",
          response("Never", 1),
          response("Rarely", 2),
          response("Sometimes", 3),
          response("Often", 4),
          response("Always", 5)
      ),
      item("FATEXP31", "In the past 7 days", "How often were you energetic?", "", 2.11341, new double[] { -1.7462, -0.0893, 1.0726, 2.3301 }, -1, "",
          response("Never", 5),
          response("Rarely", 4),
          response("Sometimes", 3),
          response("Often", 2),
          response("Always", 1)
      ),
      item("FATEXP34", "In the past 7 days", "How tired did you feel on average?", "", 3.87115, new double[] { -1.1, 0.234, 1.0103, 1.9985 }, -1, "",
          response("Not at all", 1),
          response("A little bit", 2),
          response("Somewhat", 3),
          response("Quite a bit", 4),
          response("Very much", 5)
      ),
      item("FATEXP35", "In the past 7 days", "How much were you bothered by your fatigue on average?", "", 4.22759, new double[] { -0.5079, 0.3959, 1.0696, 1.8718 }, -1, "",
          response("Not at all", 1),
          response("A little bit", 2),
          response("Somewhat", 3),
          response("Quite a bit", 4),
          response("Very much", 5)
      ),
      item("FATEXP36", "In the past 7 days", "How exhausted were you on average?", "", 3.83184, new double[] { -0.6051, 0.4513, 1.1959, 2.142 }, -1, "",
          response("Not at all", 1),
          response("A little bit", 2),
          response("Somewhat", 3),
          response("Quite a bit", 4),
          response("Very much", 5)
      ),
      item("FATEXP38", "In the past 7 days", "How fatigued were you on the day you felt most fatigued?", "", 2.91925, new double[] { -1.4219, -0.3501, 0.3455, 1.3017 }, -1, "",
          response("Not at all", 1),
          response("A little bit", 2),
          response("Somewhat", 3),
          response("Quite a bit", 4),
          response("Very much", 5)
      ),
      item("FATEXP40", "In the past 7 days", "How fatigued were you on average?", "", 4.17556, new double[] { -0.8828, 0.3275, 1.2048, 2.1884 }, -1, "",
          response("Not at all", 1),
          response("A little bit", 2),
          response("Somewhat", 3),
          response("Quite a bit", 4),
          response("Very much", 5)
      ),
      item("FATEXP41", "In the past 7 days", "How run-down did you feel on average?", "", 4.32191, new double[] { -0.5302, 0.4511, 1.1503, 2.0368 }, -1, "",
          response("Not at all", 1),
          response("A little bit", 2),
          response("Somewhat", 3),
          response("Quite a bit", 4),
          response("Very much", 5)
      ),
      item("FATEXP42", "In the past 7 days", "How much mental energy did you have on average?", "", 1.44166, new double[] { -1.2597, 0.7827, 1.9513, 3.5124 }, -1, "",
          response("Not at all", 5),
          response("A little bit", 4),
          response("Somewhat", 3),
          response("Quite a bit", 2),
          response("Very much", 1)
      ),
      item("FATEXP43", "In the past 7 days", "How physically drained were you on average?", "", 3.80743, new double[] { -0.7569, 0.3415, 1.1897, 2.1345 }, -1, "",
          response("Not at all", 1),
          response("A little bit", 2),
          response("Somewhat", 3),
          response("Quite a bit", 4),
          response("Very much", 5)
      ),
      item("FATEXP44", "In the past 7 days", "How energetic were you on average?", "", 1.98044, new double[] { -1.7359, -0.1937, 1.0159, 2.2215 }, -1, "",
          response("Not at all", 5),
          response("A little bit", 4),
          response("Somewhat", 3),
          response("Quite a bit", 2),
          response("Very much", 1)
      ),
      item("FATEXP45", "In the past 7 days", "How sluggish were you on average?", "", 3.38777, new double[] { -0.7113, 0.4086, 1.2168, 2.3337 }, -1, "",
          response("Not at all", 1),
          response("A little bit", 2),
          response("Somewhat", 3),
          response("Quite a bit", 4),
          response("Very much", 5)
      ),
      item("FATEXP46", "In the past 7 days", "On how many days was your fatigue worse in the morning?", "", 1.49214, new double[] { 0.1303, 0.657, 1.6154, 2.2495 }, -1, "",
          response("None", 1),
          response("1 day", 2),
          response("2-3 days", 3),
          response("4-5 days", 4),
          response("6-7 days", 5)
      ),
      item("FATEXP48", "In the past 7 days", "How often did you find yourself getting tired easily?", "", 3.5094, new double[] { -0.9245, -0.0283, 0.8654, 1.8096 }, -1, "",
          response("Never", 1),
          response("Rarely", 2),
          response("Sometimes", 3),
          response("Often", 4),
          response("Always", 5)
      ),
      item("FATEXP49", "In the past 7 days", "How often did you think about your fatigue?", "", 2.72679, new double[] { -0.6456, 0.3592, 1.269, 2.3007 }, -1, "",
          response("Never", 1),
          response("Rarely", 2),
          response("Sometimes", 3),
          response("Often", 4),
          response("Always", 5)
      ),
      item("FATEXP5", "In the past 7 days", "How often did you experience extreme exhaustion?", "", 2.6615, new double[] { -0.1122, 0.839, 1.7173, 2.8349 }, -1, "",
          response("Never", 1),
          response("Rarely", 2),
          response("Sometimes", 3),
          response("Often", 4),
          response("Always", 5)
      ),
      item("FATEXP50", "In the past 7 days", "How fatigued were you on the day you felt least fatigued?", "", 1.90938, new double[] { -0.3414, 0.9826, 1.9454, 2.9094 }, -1, "",
          response("Not at all", 1),
          response("A little bit", 2),
          response("Somewhat", 3),
          response("Quite a bit", 4),
          response("Very much", 5)
      ),
      item("FATEXP51", "In the past 7 days", "How easily did you find yourself getting tired on average?", "", 3.71239, new double[] { -0.8919, 0.3488, 1.1088, 2.032 }, -1, "",
          response("Not at all", 1),
          response("A little bit", 2),
          response("Somewhat", 3),
          response("Quite a bit", 4),
          response("Very much", 5)
      ),
      item("FATEXP52", "In the past 7 days", "How wiped out were you on average?", "", 3.33082, new double[] { -0.394, 0.599, 1.3903, 2.2332 }, -1, "",
          response("Not at all", 1),
          response("A little bit", 2),
          response("Somewhat", 3),
          response("Quite a bit", 4),
          response("Very much", 5)
      ),
      item("FATEXP54", "In the past 7 days", "How often did you have physical energy?", "", 2.23187, new double[] { -1.2521, 0.1559, 1.3852, 2.7361 }, -1, "",
          response("Never", 5),
          response("Rarely", 4),
          response("Sometimes", 3),
          response("Often", 2),
          response("Always", 1)
      ),
      item("FATEXP56", "In the past 7 days", "What was the level of your fatigue on most days?", "", 3.61692, new double[] { -0.8786, 0.3781, 1.6589, 2.6469 }, -1, "",
          response("None", 1),
          response("Mild", 2),
          response("Moderate", 3),
          response("Severe", 4),
          response("Very severe", 5)
      ),
      item("FATEXP6", "In the past 7 days", "How often did you feel tired even when you hadn't done anything?", "", 2.84463, new double[] { -0.6571, 0.2417, 1.2979, 2.3841 }, -1, "",
          response("Never", 1),
          response("Rarely", 2),
          response("Sometimes", 3),
          response("Often", 4),
          response("Always", 5)
      ),
      item("FATEXP7", "In the past 7 days", "How often did you feel your fatigue was beyond your control?", "", 3.2769, new double[] { 0.0178, 0.5623, 1.2602, 2.0966 }, -1, "",
          response("Never", 1),
          response("Rarely", 2),
          response("Sometimes", 3),
          response("Often", 4),
          response("Always", 5)
      ),
      item("FATIMP1", "In the past 7 days", "To what degree did you have to push yourself to get things done because of your fatigue?", "", 4.07651, new double[] { -0.5565, 0.3793, 1.008, 1.9383 }, -1, "",
          response("Not at all", 1),
          response("A little bit", 2),
          response("Somewhat", 3),
          response("Quite a bit", 4),
          response("Very much", 5)
      ),
      item("FATIMP10", "In the past 7 days", "How often did your fatigue make it difficult to start anything new?", "", 3.71355, new double[] { -0.4011, 0.3723, 1.2435, 2.3219 }, -1, "",
          response("Never", 1),
          response("Rarely", 2),
          response("Sometimes", 3),
          response("Often", 4),
          response("Always", 5)
      ),
      item("FATIMP11", "In the past 7 days", "How often did your fatigue make you more forgetful?", "", 2.70549, new double[] { -0.3095, 0.5885, 1.5804, 2.6919 }, -1, "",
          response("Never", 1),
          response("Rarely", 2),
          response("Sometimes", 3),
          response("Often", 4),
          response("Always", 5)
      ),
      item("FATIMP13", "In the past 7 days", "How often were you too tired to do errands?", "", 3.50878, new double[] { -0.3688, 0.4449, 1.3314, 2.4636 }, -1, "",
          response("Never", 1),
          response("Rarely", 2),
          response("Sometimes", 3),
          response("Often", 4),
          response("Always", 5)
      ),
      item("FATIMP14", "In the past 7 days", "How often did your fatigue make it difficult to organize your thoughts when doing things at work (include work at home)?", "", 3.17467, new double[] { -0.21, 0.6442, 1.5737, 2.602 }, -1, "",
          response("Never", 1),
          response("Rarely", 2),
          response("Sometimes", 3),
          response("Often", 4),
          response("Always", 5)
      ),
      item("FATIMP15", "In the past 7 days", "How often did your fatigue interfere with your ability to engage in recreational activities?", "", 3.56379, new double[] { -0.4385, 0.3694, 1.1899, 2.0214 }, -1, "",
          response("Never", 1),
          response("Rarely", 2),
          response("Sometimes", 3),
          response("Often", 4),
          response("Always", 5)
      ),
      item("FATIMP16", "In the past 7 days", "How often did you have trouble finishing things because of your fatigue?", "", 3.86264, new double[] { -0.3853, 0.456, 1.3312, 2.2382 }, -1, "",
          response("Never", 1),
          response("Rarely", 2),
          response("Sometimes", 3),
          response("Often", 4),
          response("Always", 5)
      ),
      item("FATIMP17", "In the past 7 days", "How often did your fatigue make it difficult to make decisions?", "", 3.25917, new double[] { -0.1303, 0.7757, 1.7017, 2.7313 }, -1, "",
          response("Never", 1),
          response("Rarely", 2),
          response("Sometimes", 3),
          response("Often", 4),
          response("Always", 5)
      ),
      item("FATIMP18", "In the past 7 days", "How often did you have to limit your social activities because of your fatigue?", "", 3.52595, new double[] { -0.224, 0.5948, 1.3756, 2.269 }, -1, "",
          response("Never", 1),
          response("Rarely", 2),
          response("Sometimes", 3),
          response("Often", 4),
          response("Always", 5)
      ),
      item("FATIMP19", "In the past 7 days", "How often were you too tired to do your household chores?", "", 3.41109, new double[] { -0.5124, 0.2993, 1.1489, 2.2027 }, -1, "",
          response("Never", 1),
          response("Rarely", 2),
          response("Sometimes", 3),
          response("Often", 4),
          response("Always", 5)
      ),
      item("FATIMP2", "In the past 7 days", "To what degree did your fatigue make you feel slowed down in your thinking?", "", 2.86203, new double[] { -0.0478, 0.845, 1.5702, 2.4288 }, -1, "",
          response("Not at all", 1),
          response("A little bit", 2),
          response("Somewhat", 3),
          response("Quite a bit", 4),
          response("Very much", 5)
      ),
      item("FATIMP20", "In the past 7 days", "How often did your fatigue make you feel less alert?", "", 3.32523, new double[] { -0.6406, 0.2992, 1.2939, 2.2197 }, -1, "",
          response("Never", 1),
          response("Rarely", 2),
          response("Sometimes", 3),
          response("Often", 4),
          response("Always", 5)
      ),
      item("FATIMP21", "In the past 7 days", "How often were you too tired to take a bath or shower?", "", 2.11414, new double[] { 0.3825, 1.1347, 2.0812, 3.3136 }, -1, "",
          response("Never", 1),
          response("Rarely", 2),
          response("Sometimes", 3),
          response("Often", 4),
          response("Always", 5)
      ),
      item("FATIMP22", "In the past 7 days", "How often did your fatigue make it difficult to organize your thoughts when doing things at home?", "", 3.12672, new double[] { -0.2396, 0.6493, 1.6027, 2.615 }, -1, "",
          response("Never", 1),
          response("Rarely", 2),
          response("Sometimes", 3),
          response("Often", 4),
          response("Always", 5)
      ),
      item("FATIMP24", "In the past 7 days", "How often did you have trouble starting things because of your fatigue?", "", 3.8138, new double[] { -0.5023, 0.3279, 1.2386, 2.3405 }, -1, "",
          response("Never", 1),
          response("Rarely", 2),
          response("Sometimes", 3),
          response("Often", 4),
          response("Always", 5)
      ),
      item("FATIMP25", "In the past 7 days", "How often was it an effort to carry on a conversation because of your fatigue?", "", 2.84088, new double[] { 0.2024, 1.1626, 2.2135, 2.9185 }, -1, "",
          response("Never", 1),
          response("Rarely", 2),
          response("Sometimes", 3),
          response("Often", 4),
          response("Always", 5)
      ),
      item("FATIMP26", "In the past 7 days", "How often were you too tired to socialize with your family?", "", 3.10719, new double[] { -0.0232, 0.7968, 1.7414, 2.5924 }, -1, "",
          response("Never", 1),
          response("Rarely", 2),
          response("Sometimes", 3),
          response("Often", 4),
          response("Always", 5)
      ),
      item("FATIMP27", "In the past 7 days", "To what degree did you have trouble starting things because of your fatigue?", "", 3.82112, new double[] { -0.3312, 0.597, 1.3039, 2.1969 }, -1, "",
          response("Not at all", 1),
          response("A little bit", 2),
          response("Somewhat", 3),
          response("Quite a bit", 4),
          response("Very much", 5)
      ),
      item("FATIMP28", "In the past 7 days", "How hard was it for you to carry on a conversation because of your fatigue?", "", 2.8066, new double[] { 0.5199, 1.374, 2.1931, 2.9323 }, -1, "",
          response("Not at all", 1),
          response("A little bit", 2),
          response("Somewhat", 3),
          response("Quite a bit", 4),
          response("Very much", 5)
      ),
      item("FATIMP29", "In the past 7 days", "How often were you too tired to leave the house?", "", 3.08762, new double[] { -0.0452, 0.6972, 1.5538, 2.6029 }, -1, "",
          response("Never", 1),
          response("Rarely", 2),
          response("Sometimes", 3),
          response("Often", 4),
          response("Always", 5)
      ),
      item("FATIMP3", "In the past 7 days", "How often did you have to push yourself to get things done because of your fatigue?", "", 4.77251, new double[] { -0.6329, 0.1258, 1.0389, 1.9415 }, -1, "",
          response("Never", 1),
          response("Rarely", 2),
          response("Sometimes", 3),
          response("Often", 4),
          response("Always", 5)
      ),
      item("FATIMP30", "In the past 7 days", "How often were you too tired to think clearly?", "", 2.96527, new double[] { -0.1065, 0.8185, 1.8163, 3.0505 }, -1, "",
          response("Never", 1),
          response("Rarely", 2),
          response("Sometimes", 3),
          response("Often", 4),
          response("Always", 5)
      ),
      item("FATIMP33", "In the past 7 days", "How often did your fatigue limit you at work (include work at home)?", "", 3.09254, new double[] { -0.5432, 0.3259, 1.3544, 2.3236 }, -1, "",
          response("Never", 1),
          response("Rarely", 2),
          response("Sometimes", 3),
          response("Often", 4),
          response("Always", 5)
      ),
      item("FATIMP34", "In the past 7 days", "To what degree did you have to limit your social activities because of your fatigue?", "", 3.28678, new double[] { 0.0066, 0.7634, 1.4442, 2.2464 }, -1, "",
          response("Not at all", 1),
          response("A little bit", 2),
          response("Somewhat", 3),
          response("Quite a bit", 4),
          response("Very much", 5)
      ),
      item("FATIMP35", "In the past 7 days", "To what degree did your fatigue make it difficult to organize your thoughts when doing things at home?", "", 3.09139, new double[] { 0.0567, 0.8543, 1.5783, 2.4216 }, -1, "",
          response("Not at all", 1),
          response("A little bit", 2),
          response("Somewhat", 3),
          response("Quite a bit", 4),
          response("Very much", 5)
      ),
      item("FATIMP36", "In the past 7 days", "To what degree did your fatigue make it difficult to start anything new?", "", 3.67666, new double[] { -0.2683, 0.5517, 1.1941, 1.9513 }, -1, "",
          response("Not at all", 1),
          response("A little bit", 2),
          response("Somewhat", 3),
          response("Quite a bit", 4),
          response("Very much", 5)
      ),
      item("FATIMP37", "In the past 7 days", "Due to your fatigue were you less effective at work (include work at home)?", "", 3.78862, new double[] { -0.2897, 0.5533, 1.2705, 1.9091 }, -1, "",
          response("Not at all", 1),
          response("A little bit", 2),
          response("Somewhat", 3),
          response("Quite a bit", 4),
          response("Very much", 5)
      ),
      item("FATIMP38", "In the past 7 days", "To what degree did your fatigue make it difficult to make decisions?", "", 2.81432, new double[] { 0.1835, 0.9384, 1.7155, 2.4172 }, -1, "",
          response("Not at all", 1),
          response("A little bit", 2),
          response("Somewhat", 3),
          response("Quite a bit", 4),
          response("Very much", 5)
      ),
      item("FATIMP4", "In the past 7 days", "How often did your fatigue interfere with your social activities?", "", 3.71365, new double[] { -0.266, 0.5159, 1.32, 2.1842 }, -1, "",
          response("Never", 1),
          response("Rarely", 2),
          response("Sometimes", 3),
          response("Often", 4),
          response("Always", 5)
      ),
      item("FATIMP40", "In the past 7 days", "How often did you have enough energy to exercise strenuously?", "", 1.17441, new double[] { -2.4817, -0.8409, 0.3359, 1.4922 }, -1, "",
          response("Never", 5),
          response("Rarely", 4),
          response("Sometimes", 3),
          response("Often", 2),
          response("Always", 1)
      ),
      item("FATIMP42", "In the past 7 days", "How often were you less effective at home due to your fatigue?", "", 3.5195, new double[] { -0.7129, 0.1792, 1.1348, 2.1626 }, -1, "",
          response("Never", 1),
          response("Rarely", 2),
          response("Sometimes", 3),
          response("Often", 4),
          response("Always", 5)
      ),
      item("FATIMP43", "In the past 7 days", "To what degree did your fatigue make it difficult to organize your thoughts when doing things at work (include work at home)?", "", 2.917, new double[] { -0.1225, 0.8023, 1.5931, 2.3911 }, -1, "",
          response("Not at all", 1),
          response("A little bit", 2),
          response("Somewhat", 3),
          response("Quite a bit", 4),
          response("Very much", 5)
      ),
      item("FATIMP44", "In the past 7 days", "To what degree did your fatigue make you more forgetful?", "", 2.36355, new double[] { -0.1149, 0.9332, 1.6754, 2.5473 }, -1, "",
          response("Not at all", 1),
          response("A little bit", 2),
          response("Somewhat", 3),
          response("Quite a bit", 4),
          response("Very much", 5)
      ),
      item("FATIMP45", "In the past 7 days", "To what degree did your fatigue interfere with your ability to engage in recreational activities?", "", 3.23518, new double[] { -0.2129, 0.5984, 1.248, 1.9911 }, -1, "",
          response("Not at all", 1),
          response("A little bit", 2),
          response("Somewhat", 3),
          response("Quite a bit", 4),
          response("Very much", 5)
      ),
      item("FATIMP47", "In the past 7 days", "To what degree did you have to force yourself to get up and do things because of your fatigue?", "", 3.67958, new double[] { -0.3228, 0.4792, 1.0985, 1.9192 }, -1, "",
          response("Not at all", 1),
          response("A little bit", 2),
          response("Somewhat", 3),
          response("Quite a bit", 4),
          response("Very much", 5)
      ),
      item("FATIMP48", "In the past 7 days", "To what degree did your fatigue interfere with your social activities?", "", 3.80565, new double[] { -0.0070, 0.7283, 1.3211, 1.9839 }, -1, "",
          response("Not at all", 1),
          response("A little bit", 2),
          response("Somewhat", 3),
          response("Quite a bit", 4),
          response("Very much", 5)
      ),
      item("FATIMP49", "In the past 7 days", "To what degree did your fatigue interfere with your physical functioning?", "", 4.02223, new double[] { -0.1864, 0.667, 1.3071, 2.0529 }, -1, "",
          response("Not at all", 1),
          response("A little bit", 2),
          response("Somewhat", 3),
          response("Quite a bit", 4),
          response("Very much", 5)
      ),
      item("FATIMP5", "In the past 7 days", "How often were you less effective at work due to your fatigue (include work at home)?", "", 3.51903, new double[] { -0.5312, 0.3064, 1.243, 2.1271 }, -1, "",
          response("Never", 1),
          response("Rarely", 2),
          response("Sometimes", 3),
          response("Often", 4),
          response("Always", 5)
      ),
      item("FATIMP50", "In the past 7 days", "Did fatigue make you less effective at home?", "", 3.99757, new double[] { -0.3614, 0.5084, 1.1872, 1.8793 }, -1, "",
          response("Not at all", 1),
          response("A little bit", 2),
          response("Somewhat", 3),
          response("Quite a bit", 4),
          response("Very much", 5)
      ),
      item("FATIMP51", "In the past 7 days", "To what degree did you have trouble finishing things because of your fatigue?", "", 3.80042, new double[] { -0.2108, 0.6614, 1.3035, 2.1422 }, -1, "",
          response("Not at all", 1),
          response("A little bit", 2),
          response("Somewhat", 3),
          response("Quite a bit", 4),
          response("Very much", 5)
      ),
      item("FATIMP52", "In the past 7 days", "To what degree did your fatigue make you feel less alert?", "", 3.1125, new double[] { -0.3652, 0.6392, 1.3814, 2.3044 }, -1, "",
          response("Not at all", 1),
          response("A little bit", 2),
          response("Somewhat", 3),
          response("Quite a bit", 4),
          response("Very much", 5)
      ),
      item("FATIMP53", "In the past 7 days", "How often were you too tired to take a short walk?", "", 2.40867, new double[] { -0.3316, 0.3922, 1.2166, 2.1705 }, -1, "",
          response("Never", 1),
          response("Rarely", 2),
          response("Sometimes", 3),
          response("Often", 4),
          response("Always", 5)
      ),
      item("FATIMP55", "In the past 7 days", "How often did you have to force yourself to get up and do things because of your fatigue?", "", 3.51173, new double[] { -0.554, 0.2337, 1.1005, 2.1064 }, -1, "",
          response("Never", 1),
          response("Rarely", 2),
          response("Sometimes", 3),
          response("Often", 4),
          response("Always", 5)
      ),
      item("FATIMP56", "In the past 7 days", "How often were you too tired to socialize with your friends?", "", 2.87279, new double[] { -0.2469, 0.5605, 1.4281, 2.3837 }, -1, "",
          response("Never", 1),
          response("Rarely", 2),
          response("Sometimes", 3),
          response("Often", 4),
          response("Always", 5)
      ),
      item("FATIMP6", "In the past 7 days", "How often did your fatigue make you feel slowed down in your thinking?", "", 2.97303, new double[] { -0.3346, 0.5598, 1.524, 2.4336 }, -1, "",
          response("Never", 1),
          response("Rarely", 2),
          response("Sometimes", 3),
          response("Often", 4),
          response("Always", 5)
      ),
      item("FATIMP8", "In the past 7 days", "How often were you too tired to watch television?", "", 1.69742, new double[] { -0.0752, 1.0017, 2.2376, 3.6673 }, -1, "",
          response("Never", 1),
          response("Rarely", 2),
          response("Sometimes", 3),
          response("Often", 4),
          response("Always", 5)
      ),
      item("FATIMP9", "In the past 7 days", "How often did your fatigue make it difficult to plan activities ahead of time?", "", 3.48196, new double[] { -0.0397, 0.7032, 1.4657, 2.4086 }, -1, "",
          response("Never", 1),
          response("Rarely", 2),
          response("Sometimes", 3),
          response("Often", 4),
          response("Always", 5)
      ),
      item("HI12", "During the past 7 days:", "I feel weak all over", "", 2.6948, new double[] { 0.1605, 0.9156, 1.6605, 2.4206 }, -1, "",
          response("Not at all", 1),
          response("A little bit", 2),
          response("Somewhat", 3),
          response("Quite a bit", 4),
          response("Very much", 5)
      ),
      item("HI7", "During the past 7 days:", "I feel fatigued", "", 4.32034, new double[] { -1.1444, 0.0806, 0.9561, 1.772 }, -1, "",
          response("Not at all", 1),
          response("A little bit", 2),
          response("Somewhat", 3),
          response("Quite a bit", 4),
          response("Very much", 5)
      )
  );

  public static ItemBank bank() {
    return bank;
  }
}
